import Link from "next/link";
import { PageHero, SectionHeading, Steps, FAQ, CtaBand } from "@/components/Editorial";
import AssessmentForm from "@/components/AssessmentForm";
import "./assessment.css";

export const metadata = { title:"Avaliação de Terceiros", description:"Conheça os controles de segurança e privacidade de fornecedores. Gere Security Score, Privacy Score, relatório e plano de ação orientativos." };
export default function AssessmentPage() {
  return <main id="conteudo"><PageHero eyebrow="Avaliação de Terceiros" title="Confiança começa com informação." description="Conheça as práticas de segurança e privacidade da empresa avaliada, identifique pontos de atenção e organize os próximos passos na gestão de fornecedores."><p className="page-kicker">Da resposta à ação</p><ul className="feature-list"><li>Security Score e Privacy Score</li><li>Questionário com 12 controles</li><li>Relatório e plano de ação</li><li>Área privada para evidências</li></ul><a href="#avaliacao" className="button button--navy">Iniciar avaliação ↗</a></PageHero>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Como funciona" title="Clareza em cada etapa." description="Esta ferramenta oferece uma autoavaliação inicial. Para um processo de homologação ou decisão contratual, combine as respostas com análise especializada e evidências verificadas." /><Steps items={[{title:"Informe o contexto",description:"Identifique a empresa avaliada, seu setor e a pessoa responsável pelas respostas."},{title:"Avalie os controles",description:"Indique práticas implementadas, parciais e pontos que ainda precisam ser desenvolvidos."},{title:"Priorize melhorias",description:"Receba indicadores por domínio e recomendações para organizar as próximas ações."},{title:"Reúna as evidências",description:"Guarde o link privado, anexe documentos e exporte seu relatório e o plano de ação."}]} /></div></section>
    <AssessmentForm />
    <section className="section"><div className="shell narrow"><SectionHeading eyebrow="Dúvidas frequentes" title="Antes de começar." /><FAQ items={[
      {question:"Quem pode responder à avaliação?",answer:"Um responsável da empresa avaliada que conheça as práticas do ambiente e tenha autorização para fornecer as informações. Se necessário, reúna os dados com as áreas de tecnologia, gestão e privacidade. A precisão das respostas e das evidências determina a utilidade do resultado."},
      {question:"Como a avaliação começa?",answer:"O contratante indica a empresa terceira, e a Plataforma de Privacidade entra em contato diretamente com a empresa avaliada para conduzir o processo, formalizar a avaliação e liberar o acesso à plataforma."},
      {question:"Como os scores são calculados?",answer:"Depende do que for contratado. A empresa pode contratar somente a avaliação de privacidade ou somente a avaliação de segurança. A avaliação de privacidade se baseia em frameworks da área de privacidade, e a avaliação de segurança se baseia em frameworks da área de segurança. Cada score corresponde a uma escala de 100 pontos: implementado vale 100, parcialmente implementado vale 50 e não implementado vale 0. Não se aplica fica fora do cálculo. Os detalhes das perguntas e das evidências são apresentados no momento da contratação e enviados junto com o relatório."},
      {question:"O resultado é uma certificação?",answer:"Não. O resultado é uma avaliação especializada conduzida pela Plataforma de Privacidade com base em frameworks reconhecidos, e não uma certificação. Ele orienta a decisão do contratante e o plano de melhoria da empresa avaliada, sem substituir processos de certificação formais."},
      {question:"Como funcionam as evidências?",answer:"Durante a avaliação, a empresa envia os documentos comprobatórios pela plataforma, em arquivos PDF, PNG ou JPEG de até 5 MB cada. As evidências ficam vinculadas à avaliação, são analisadas pela Plataforma de Privacidade e fundamentam o relatório, o plano de ação e os scores."},
      {question:"Como acesso o relatório depois?",answer:"Pela Área do Cliente, com login e senha. A empresa avaliada acessa o próprio processo de avaliação, e o contratante acessa os resultados dos fornecedores vinculados à sua conta. Ambos recebem o relatório completo, o plano de ação e a área de evidências."},
      {question:"Posso levar o plano para a minha equipe?",answer:"Sim. O relatório e o plano de ação podem ser baixados e compartilhados com pessoas autorizadas da sua equipe. O plano inclui recomendações com campos para responsável, prazo e acompanhamento."},
    ]} /></div></section><CtaBand title="Precisa estruturar a avaliação da sua cadeia de fornecedores?" description="Converse sobre criticidade, critérios, revisão documental e acompanhamento dos planos de ação." href="/contato?interesse=terceiros" label="Conversar sobre terceiros ↗" />
  </main>;
}
