import { test, expect } from "@playwright/test";
import { readdirSync, readFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { assessmentQuestions } from "../lib/assessment.js";
import { registrationCode, localEmail } from "./email-helper.mjs";
import { generateSync } from "otplib";

test("segurança administrativa: ativar autenticador, recuperar login e consultar operação", async ({ page }) => {
  const headers = { Origin: "http://127.0.0.1:3100" }, email = "mfa-ui@example.invalid", password = "senha de teste de autenticador";
  expect((await page.request.post("/api/auth/cadastro", { headers, data: { name: "Admin Autenticador", email, password, terms: true } })).status()).toBe(202);
  expect((await page.request.post("/api/auth/confirmar-cadastro", { headers, data: { code: registrationCode(process.env.PORTFOLIO_TEST_DATA_DIR, email) } })).status()).toBe(201);
  const store = new DatabaseSync(path.join(process.env.PORTFOLIO_TEST_DATA_DIR, "portfolio.sqlite"));
  try { const user = store.prepare("SELECT id FROM users WHERE email=?").get(email); store.prepare("INSERT INTO user_access(user_id,role) VALUES(?,'admin')").run(user.id); }
  finally { store.close(); }
  await page.goto("/minha-conta/configuracoes");
  const form = page.getByRole("form", { name: "Configurar duas etapas", exact: true });
  await form.getByLabel("Confirme sua senha").fill(password);
  const configured = page.waitForResponse(response => response.url().endsWith("/api/auth/configurar-2fa"));
  await form.getByRole("button", { name: "Configurar aplicativo", exact: true }).click();
  const setup = await (await configured).json();
  await expect(page.getByRole("img", { name: "QR code para adicionar a conta ao aplicativo autenticador" })).toBeVisible();
  const confirmation = page.getByRole("form", { name: "Confirmar ativação de duas etapas", exact: true });
  await confirmation.getByLabel("Código do aplicativo").fill(generateSync({ secret: setup.secret }));
  const activation = page.waitForResponse(response => response.url().endsWith("/api/auth/ativar-2fa"));
  await confirmation.getByRole("button", { name: "Ativar proteção", exact: true }).click();
  const result = await (await activation).json();
  await expect(page.getByRole("heading", { name: "Guarde seus códigos de recuperação" })).toBeVisible();
  await page.screenshot({ path: "test-results/seguranca-configuracao-desktop.png", fullPage: true });
  expect((await page.request.post("/api/auth/sair", { headers, data: {} })).status()).toBe(200);
  await page.goto("/login");
  await page.getByLabel("E-mail", { exact: true }).fill(email); await page.getByLabel("Senha", { exact: true }).fill(password);
  await page.getByRole("button", { name: /Entrar/ }).click();
  await expect(page.getByRole("heading", { name: "Confirme seu acesso" })).toBeVisible();
  await page.getByLabel("Código de autenticação").fill(result.recoveryCodes[0]);
  await page.getByRole("button", { name: /Confirmar acesso/ }).click();
  await expect(page).toHaveURL(/\/minha-conta$/);
  await page.goto("/administracao?tab=operacao");
  await expect(page.getByRole("heading", { name: "Histórico de segurança" })).toBeVisible();
  await expect(page.getByText("Código de recuperação utilizado", { exact: true })).toBeVisible();
  await expect(page.getByText("Admin Autenticador", { exact: true }).first()).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/operacao-mobile.png", fullPage: true });
});

test("transições entre páginas: animações, retorno e movimento reduzido", async ({ page }) => {
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.addInitScript(() => {
    window.routeTransitions = [];
    const nativeTransition = document.startViewTransition?.bind(document);
    if (!nativeTransition) return;
    document.startViewTransition = (...args) => {
      const transition = nativeTransition(...args);
      transition.ready.then(() => {
        window.routeTransitions.push({
          kind: document.querySelector(".page-motion")?.dataset.pageKind,
          animations: document.getAnimations().map(animation => animation.animationName).filter(Boolean),
        });
      }).catch(() => {});
      return transition;
    };
  });
  await page.goto("/");
  const navigation = page.getByRole("navigation", { name: "Navegação principal", exact: true });
  await navigation.getByRole("link", { name: "Privacidade", exact: true }).click();
  await expect(page).toHaveURL(/consultoria-em-privacidade$/);
  await expect.poll(() => page.evaluate(() => window.routeTransitions.some(item => item.kind === "marketing" && item.animations.includes("page-arrive")))).toBe(true);
  await navigation.getByRole("link", { name: "Hub Educacional", exact: true }).click();
  await expect(page).toHaveURL(/hub-educacional$/);
  await expect.poll(() => page.evaluate(() => window.routeTransitions.some(item => item.kind === "learning" && item.animations.includes("page-discover")))).toBe(true);
  await page.goBack();
  await expect(page).toHaveURL(/consultoria-em-privacidade$/);
  await navigation.getByRole("link", { name: "Contato", exact: true }).click();
  await expect(page).toHaveURL(/contato$/);
  await expect.poll(() => page.evaluate(() => window.routeTransitions.some(item => item.kind === "form" && item.animations.includes("page-focus")))).toBe(true);
  await page.getByLabel("Nome completo").fill("Navegação fluida");
  await page.locator(".site-footer").getByRole("link", { name: "Política de Privacidade", exact: true }).click();
  await expect(page).toHaveURL(/politica-de-privacidade$/);
  await expect.poll(() => page.evaluate(() => window.routeTransitions.some(item => item.kind === "reading" && item.animations.includes("page-read")))).toBe(true);
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.evaluate(() => { window.routeTransitions = []; });
  await navigation.getByRole("link", { name: "Hub Educacional", exact: true }).click();
  await expect(page).toHaveURL(/hub-educacional$/);
  await expect(page.locator(".page-motion")).toHaveAttribute("data-page-kind", "learning");
  await expect.poll(() => page.evaluate(() => getComputedStyle(document.querySelector(".page-hero__inner>div")).animationName)).toBe("none");
  expect(await page.evaluate(() => window.routeTransitions.every(item => item.animations.length === 0))).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("button", { name: "Abrir menu", exact: true }).click();
  await navigation.getByRole("link", { name: "Sobre", exact: true }).click();
  await expect(page).toHaveURL(/sobre$/);
  await expect(page.getByRole("button", { name: "Abrir menu", exact: true })).toHaveAttribute("aria-expanded", "false");
  expect(errors).toEqual([]);
});

test("portal de usuário, cliente e administração", async ({ page }) => {
  const headers = { Origin: "http://127.0.0.1:3100" };
  const registered = await page.request.post("/api/auth/cadastro", { headers, data: { name: "Cliente portal", email: "portal-ui@example.invalid", password: "frase longa portal teste", terms: true } });
  expect(registered.status()).toBe(202);
  expect((await page.request.post("/api/auth/confirmar-cadastro", { headers, data: { code: registrationCode(process.env.PORTFOLIO_TEST_DATA_DIR, "portal-ui@example.invalid") } })).status()).toBe(201);
  await page.goto("/minha-conta");
  const guide = page.getByRole("region", { name: "Comece pela sua primeira avaliação.", exact: true });
  await expect(guide).toBeVisible();
  await expect(guide.getByRole("listitem")).toHaveCount(3);
  await expect(page.locator(".account-summary-metrics")).toHaveCount(0);
  await expect(page.getByRole("form", { name: "Atualizar perfil", exact: true })).toHaveCount(0);
  await expect(page.getByRole("form", { name: "Alterar senha", exact: true })).toHaveCount(0);
  await expect(page.getByRole("navigation", { name: "Área da conta", exact: true }).getByRole("link", { name: "Documentos", exact: true })).toHaveCount(0);
  await page.goto("/minha-conta/documentos");
  await expect(page).toHaveURL(/\/minha-conta$/); // O servidor também restringe a seção, além do menu.
  await page.goto("/minha-conta/atendimento");
  await expect(page).toHaveURL(/\/minha-conta$/);
  mkdirSync("test-results", { recursive: true });
  await page.screenshot({ path: "test-results/primeiro-acesso-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/primeiro-acesso-mobile.png", fullPage: true });
  await guide.getByRole("link", { name: "Conhecer os materiais de apoio" }).click();
  await expect(page).toHaveURL(/\/minha-conta\/materiais$/);
  await expect(page.getByRole("heading", { name: "Materiais para começar", exact: true })).toBeInViewport();
  await page.getByRole("button", { name: "Abrir navegação da conta", exact: true }).click();
  await page.getByRole("navigation", { name: "Área da conta", exact: true }).getByRole("link", { name: "Visão geral", exact: true }).click();
  await expect(page.getByRole("button", { name: "Abrir navegação da conta", exact: true })).toHaveAttribute("aria-expanded", "false");
  await expect(guide).toBeVisible();
  await guide.getByRole("link", { name: "Fazer minha primeira avaliação", exact: true }).click();
  await expect(page).toHaveURL(/\/avaliacao-de-terceiros#avaliacao$/);
  await expect(page.getByRole("heading", { name: "Vamos conhecer a empresa avaliada", exact: true })).toBeVisible();
  await page.goto("/minha-conta");
  await expect(guide).toBeVisible(); // O guia continua disponível enquanto não houver uma avaliação concluída.
  await page.setViewportSize({ width: 1440, height: 1000 });
  const created = await page.request.post("/api/avaliacoes", { headers, data: { company: "Empresa Portal", name: "Cliente", email: "portal-ui@example.invalid", sector: "Tecnologia", consent: true, answers: Object.fromEntries(assessmentQuestions.map(item => [item.id, "no"])) } });
  expect(created.status()).toBe(201);
  const assessment = await created.json();
  expect(assessment.token).toBeUndefined();
  await page.goto("/minha-conta");
  await expect(guide).toHaveCount(0);
  await expect(page.locator(".account-summary-metrics")).toBeVisible();
  await expect(page.locator(".account-recent-card")).toContainText("Empresa Portal");
  await expect(page.locator(".account-focus-card")).toContainText("Próxima".toUpperCase());
  await page.getByRole("navigation", { name: "Área da conta", exact: true }).getByRole("link", { name: "Avaliações", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Minhas avaliações", exact: true })).toBeVisible();
  await expect(page.getByRole("table")).toContainText("Empresa Portal");
  await expect(page.getByRole("heading", { name: "Plano de ação", exact: true })).toHaveCount(0);
  expect((await page.request.get("/api/portal/material")).status()).toBe(200);
  await page.getByRole("link", { name: "Abrir relatório", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Security Score", exact: true })).toBeVisible();
  const db = new DatabaseSync(path.join(process.env.PORTFOLIO_TEST_DATA_DIR, "portfolio.sqlite"));
  try {
    const user = db.prepare("SELECT id FROM users WHERE email=?").get("portal-ui@example.invalid");
    db.prepare("INSERT INTO user_access(user_id,role) VALUES(?,'cliente')").run(user.id);
    await page.goto("/minha-conta/documentos");
    await expect(page.locator("#documentos")).toContainText("Reúna os documentos da avaliação");
    await expect(page.getByRole("link", { name: "Anexar ao relatório mais recente" })).toHaveAttribute("href", `/avaliacao-de-terceiros/relatorio/${assessment.id}#evidence-title`);
    await page.goto("/minha-conta/servicos");
    await expect(page.getByRole("link", { name: "Falar com a equipe pelo atendimento" })).toHaveAttribute("href", "/minha-conta/atendimento");
    db.prepare("INSERT INTO client_services(id,user_id,title,description,status,due_date,updated_at) VALUES('ui-service',?,?,?,'andamento','2027-02-15',?)")
      .run(user.id, "Consultoria em andamento", "Revisão dos processos de segurança", Date.now());
    await page.goto("/minha-conta");
    await page.getByRole("link", { name: "Abrir tarefa", exact: true }).click();
    await expect(page).toHaveURL(/\/minha-conta\/plano\?avaliacao=/);
    const task = page.locator("#plano form").first();
    await expect(task).toBeVisible();
    await task.getByLabel("Responsável").fill("Equipe TI");
    await task.getByLabel("Prazo").fill("2027-01-15");
    await task.getByLabel("Status").selectOption("andamento");
    await task.getByRole("button").click();
    await expect(task.getByRole("status")).toContainText("salvas");
    await page.goto("/minha-conta/atendimento");
    await page.locator(".account-new-request summary").click();
    const request = page.getByRole("form", { name: "Enviar solicitação", exact: true });
    await request.getByLabel("Assunto").fill("Apoio no diagnóstico");
    await request.getByLabel("Mensagem").fill("Gostaria de revisar o diagnóstico.");
    await request.getByRole("button").click();
    await expect(page.locator("#atendimento h4")).toContainText("Apoio no diagnóstico");
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    db.prepare("UPDATE user_access SET role='admin' WHERE user_id=?").run(user.id);
    await page.goto("/minha-conta");
    await expect(page.getByText("PAINEL DO ADMINISTRADOR", { exact: true })).toBeVisible();
    await expect(page.getByRole("region", { name: "Suas prioridades", exact: true })).toContainText("Empresa Portal");
    await expect(guide).toHaveCount(0);
    await page.getByRole("link", { name: "Abrir administração" }).click();
    await expect(page.getByRole("heading", { name: "Visão geral", exact: true })).toBeVisible();
    await expect(page.getByRole("link", { name: /Solicitações em aberto/ })).toContainText("1");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    mkdirSync("test-results", { recursive: true });
    await page.screenshot({ path: "test-results/admin-mobile.png", fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto("/administracao");
    await page.screenshot({ path: "test-results/admin-desktop.png", fullPage: true });
    await page.getByRole("navigation", { name: "Administração", exact: true }).getByRole("link", { name: "Usuários", exact: true }).click();
    const filters = page.getByRole("form", { name: "Filtrar registros" });
    await filters.getByLabel("Pesquisar", { exact: true }).fill("inexistente");
    await filters.getByRole("button", { name: "Filtrar", exact: true }).click();
    await expect(page.getByText("Nenhum usuário encontrado", { exact: true })).toBeVisible();
    await filters.getByLabel("Pesquisar", { exact: true }).fill("portal-ui@");
    await filters.getByRole("combobox", { name: "Perfil", exact: true }).selectOption("admin");
    await filters.getByRole("combobox", { name: "Solicitações", exact: true }).selectOption("ativas");
    await filters.getByRole("button", { name: "Filtrar", exact: true }).click();
    await expect(page.locator(".admin-user")).toHaveCount(1);
    await expect(page.locator(".admin-user")).toContainText("Email confirmado");
    await page.getByRole("link", { name: "1 solicitações em aberto" }).click();
    const reply = page.getByRole("form", { name: "Responder: Apoio no diagnóstico", exact: true });
    await reply.getByLabel("Resposta").fill("Vamos agendar a revisão.");
    await reply.getByLabel("Status").selectOption("andamento");
    await reply.getByRole("button").click();
    await expect(reply.getByRole("status")).toContainText("salvas");
    await page.getByRole("navigation", { name: "Administração", exact: true }).getByRole("link", { name: "Emails", exact: true }).click();
    await filters.getByLabel("Pesquisar", { exact: true }).fill("portal-ui@");
    await filters.getByRole("combobox", { name: "Tipo de envio", exact: true }).selectOption("cadastro");
    await filters.getByRole("button", { name: "Filtrar", exact: true }).click();
    await expect(page.getByRole("table")).toContainText("Somente local");
    await expect(page.getByRole("table")).toContainText("Código de cadastro");
    db.prepare("INSERT INTO email_events(id,created_at,completed_at,recipient,subject,category,status,smtp_code,error_code,error_message) VALUES('ui-failure',?,?,?,'Teste SMTP','teste','failed',535,'EAUTH',?)")
      .run(Date.now(), Date.now(), "falha@example.invalid", "Autenticação recusada pelo servidor SMTP.");
    await page.goto("/administracao?tab=emails&status=failed&period=1");
    await expect(page.getByRole("table")).toContainText("falha@example.invalid");
    await expect(page.getByRole("table")).toContainText("SMTP 535");
    await expect(page.getByRole("table")).toContainText("Autenticação recusada");
    await expect(page.getByRole("table")).not.toContainText("portal-ui@example.invalid");
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    db.prepare("UPDATE user_access SET role='cliente' WHERE user_id=?").run(user.id);
    await page.goto("/minha-conta");
    await expect(page.locator(".account-attention")).toContainText("1 resposta aguardando leitura");
    await expect(page.locator(".account-recent-card")).toContainText("Empresa Portal");
    await expect(page.locator(".account-overview-bottom")).toContainText("Consultoria em andamento");
    await page.screenshot({ path: "test-results/conta-cliente-mobile.png", fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.screenshot({ path: "test-results/conta-cliente-desktop.png", fullPage: true });
    await page.getByRole("link", { name: "Apoio no diagnóstico", exact: true }).click();
    await expect(page.locator("#atendimento blockquote")).toContainText("Vamos agendar a revisão");
    await page.getByRole("button", { name: "Marcar como lida", exact: true }).click();
    await expect(page.locator(".account-read-status")).toContainText("Resposta lida");
    await page.reload();
    await expect(page.locator(".account-read-status")).toContainText("Resposta lida");
    await page.goto("/minha-conta");
    await expect(page.locator(".account-attention")).toHaveCount(0);
    await page.goto("/minha-conta/plano");
    await page.locator("#plano summary").click();
    await expect(page.locator("#plano form").first().getByLabel("Responsável")).toHaveValue("Equipe TI");
    await page.goto("/administracao");
    await expect(page).toHaveURL(/\/minha-conta$/);
  } finally { db.close(); }
});

test("autenticação: cadastro, sessão, perfil, senha e recuperação", async ({ page }) => {
  const password = "minha frase de teste 123";
  const newPassword = "outra frase de teste 456";
  const address = "auth-ui@example.invalid";
  await page.goto("/minha-conta");
  await expect(page).toHaveURL(/\/login$/);
  await page.getByRole("link", { name: "Cadastre-se" }).click();
  await page.getByLabel("Nome completo").fill("Usuário de teste");
  await page.getByLabel("E-mail", { exact: true }).fill(address);
  await page.getByLabel("Senha", { exact: true }).fill(password);
  await page.getByLabel("Confirmar senha").fill(password);
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Criar conta" }).click();
  await expect(page).toHaveURL(/\/confirmar-cadastro$/);
  await page.reload();
  await page.getByLabel("Código de confirmação").fill(registrationCode(process.env.PORTFOLIO_TEST_DATA_DIR, address));
  await page.getByRole("button", { name: "Confirmar e criar conta" }).click();
  await expect(page).toHaveURL(/\/minha-conta$/);
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Usuário de teste");
  expect(await page.evaluate(() => document.cookie)).not.toContain("portfolio_session");
  await page.reload();
  await expect(page).toHaveURL(/\/minha-conta$/);
  await expect(page.getByRole("form", { name: "Atualizar perfil", exact: true })).toHaveCount(0);
  await page.getByRole("navigation", { name: "Área da conta", exact: true }).getByRole("link", { name: "Configurações", exact: true }).click();
  await expect(page).toHaveURL(/\/minha-conta\/configuracoes$/);
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Configurações");
  await page.getByLabel("Nome completo").fill("Nome atualizado");
  await page.getByRole("button", { name: "Salvar nome" }).click();
  await expect(page.getByRole("status")).toContainText("Nome atualizado");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByLabel("Senha atual", { exact: true }).fill(password);
  await page.getByLabel("Nova senha", { exact: true }).fill(newPassword);
  await page.getByLabel("Confirmar nova senha").fill(newPassword);
  await page.getByRole("button", { name: "Alterar senha", exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  await page.getByLabel("E-mail", { exact: true }).fill(address);
  await page.getByLabel("Senha", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Entrar", exact: true }).click();
  await expect(page.locator("form [role=alert]")).toContainText("incorretos");
  await page.getByLabel("Senha", { exact: true }).fill(newPassword);
  await page.getByRole("button", { name: "Entrar", exact: true }).click();
  await expect(page).toHaveURL(/\/minha-conta$/);
  await page.getByRole("button", { name: "Sair da conta" }).click();
  await expect(page).toHaveURL(/\/login$/);
  await page.goto("/minha-conta");
  await expect(page).toHaveURL(/\/login$/);
  await page.getByRole("link", { name: "Esqueci minha senha" }).click();
  await expect(page).toHaveURL(/\/recuperar-senha$/);
  await page.getByLabel("E-mail", { exact: true }).fill(address);
  await page.getByRole("button", { name: "Solicitar recuperação" }).click();
  await expect(page.getByRole("status")).toContainText("caixa de testes local");
  const token = localEmail(process.env.PORTFOLIO_TEST_DATA_DIR, address, /redefinir-senha#([\w-]{43})/)[1];
  await page.goto(`/redefinir-senha#${token}`);
  await page.getByLabel("Senha", { exact: true }).fill(password);
  await page.getByLabel("Confirmar senha").fill(password);
  await page.getByRole("button", { name: "Redefinir senha" }).click();
  await expect(page.getByRole("status")).toContainText("Senha redefinida");
  await expect(page).toHaveURL(/\/redefinir-senha$/);
  await page.getByRole("link", { name: "Voltar para o login" }).click();
  await page.getByLabel("E-mail", { exact: true }).fill(address);
  await page.getByLabel("Senha", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Entrar", exact: true }).click();
  await expect(page).toHaveURL(/\/minha-conta$/);
});

test("administração: exclusão confirmada, cancelamento e revogação de acesso", async ({ page, browser }) => {
  const headers = { Origin: "http://127.0.0.1:3100" };
  const targetContext = await browser.newContext({ baseURL: "http://127.0.0.1:3100" });
  let db;
  try {
    for (const [api, name, email] of [[targetContext.request, "Conta para excluir", "excluir-ui@example.invalid"], [page.request, "Administrador exclusão", "operador-exclusao-ui@example.invalid"]]) {
      expect((await api.post("/api/auth/cadastro", { headers, data: { name, email, password: "frase longa exclusao teste", terms: true } })).status()).toBe(202);
      expect((await api.post("/api/auth/confirmar-cadastro", { headers, data: { code: registrationCode(process.env.PORTFOLIO_TEST_DATA_DIR, email) } })).status()).toBe(201);
    }
    db = new DatabaseSync(path.join(process.env.PORTFOLIO_TEST_DATA_DIR, "portfolio.sqlite"));
    db.exec("PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");
    const target = db.prepare("SELECT id,email FROM users WHERE email='excluir-ui@example.invalid'").get();
    const admin = db.prepare("SELECT id,email FROM users WHERE email='operador-exclusao-ui@example.invalid'").get();
    db.prepare("INSERT INTO user_access(user_id,role) VALUES(?,'admin')").run(admin.id);
    const reportResponse = await targetContext.request.post("/api/avaliacoes", { headers, data: { company: "Empresa a excluir", name: "Conta para excluir", email: target.email, sector: "Tecnologia", consent: true, answers: Object.fromEntries(assessmentQuestions.map(item => [item.id, "no"])) } });
    expect(reportResponse.status()).toBe(201);
    const report = await reportResponse.json();
    expect((await targetContext.request.get(`/api/avaliacoes/${report.id}`)).status()).toBe(200);

    await page.goto(`/administracao?tab=usuarios&q=${admin.email}`);
    await expect(page.getByRole("button", { name: "Excluir conta", exact: true })).toBeDisabled();
    await expect(page.locator(".admin-user-delete")).toContainText("Você não pode excluir a própria conta.");
    await page.goto(`/administracao?tab=usuarios&q=${target.email}`);
    const opener = page.getByRole("button", { name: "Excluir conta", exact: true });
    const dialog = page.getByRole("dialog", { name: "Excluir esta conta?", exact: true });
    let requests = 0;
    page.on("request", request => { if (request.url().endsWith("/api/portal/excluir-conta")) requests++; });
    await opener.click();
    await expect(dialog).toBeVisible();
    await expect(dialog).toContainText("Conta para excluir");
    await expect(dialog).toContainText(target.email);
    const confirm = dialog.getByRole("button", { name: "Excluir definitivamente", exact: true });
    await expect(confirm).toBeDisabled();
    await dialog.getByLabel("Digite o email da conta para confirmar").fill("outra-conta@example.invalid");
    await expect(confirm).toBeDisabled();
    await dialog.getByRole("button", { name: "Cancelar", exact: true }).click();
    await expect(dialog).not.toBeVisible();
    await expect(opener).toBeFocused();
    expect(requests).toBe(0);
    expect(db.prepare("SELECT id FROM users WHERE id=?").get(target.id)).toBeTruthy();
    await opener.click();
    await expect(dialog.getByLabel("Digite o email da conta para confirmar")).toHaveValue("");
    await page.keyboard.press("Escape");
    await expect(dialog).not.toBeVisible();
    expect(requests).toBe(0);

    await page.setViewportSize({ width: 390, height: 844 });
    await opener.click();
    await expect(dialog).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    const bounds = await dialog.boundingBox();
    expect(bounds.x).toBeGreaterThanOrEqual(0);
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(390);
    await page.screenshot({ path: "test-results/exclusao-conta-mobile.png" });
    await dialog.getByLabel("Digite o email da conta para confirmar").fill(target.email);
    await expect(confirm).toBeEnabled();
    const removed = page.waitForResponse(response => response.url().endsWith("/api/portal/excluir-conta") && response.request().method() === "POST");
    await confirm.click();
    expect((await removed).status()).toBe(200);
    await expect(page.getByRole("status")).toContainText("A conta de Conta para excluir foi excluída com sucesso.");
    await expect(page.locator(".admin-user")).toHaveCount(0);
    expect(requests).toBe(1);
    expect(db.prepare("SELECT id FROM users WHERE id=?").get(target.id)).toBeUndefined();
    expect(db.prepare("SELECT id FROM assessments WHERE id=?").get(report.id)).toBeUndefined();
    expect((await targetContext.request.get(`/api/avaliacoes/${report.id}`)).status()).toBe(404);
    expect((await targetContext.request.post("/api/auth/perfil", { headers, data: { name: "Sessão excluída" } })).status()).toBe(401);
    await page.reload();
    await expect(page.getByText("Nenhum usuário encontrado", { exact: true })).toBeVisible();
    await page.goto(`/administracao?tab=usuarios&q=${admin.email}`);
    await expect(page.locator(".admin-user")).toHaveCount(1);
    await expect(page.getByRole("button", { name: "Excluir conta", exact: true })).toBeDisabled();
  } finally { db?.close(); await targetContext.close(); }
});

test("administração: edição de contas, conflitos e login com email atualizado", async ({ page, browser }) => {
  const headers = { Origin: "http://127.0.0.1:3100" }, password = "frase longa edicao teste";
  const targetContext = await browser.newContext({ baseURL: "http://127.0.0.1:3100" });
  let db;
  try {
    for (const [api, name, email] of [[targetContext.request, "Conta de edição", "editar-ui@example.invalid"], [page.request, "Administrador edição", "operador-edicao-ui@example.invalid"]]) {
      expect((await api.post("/api/auth/cadastro", { headers, data: { name, email, password, terms: true } })).status()).toBe(202);
      expect((await api.post("/api/auth/confirmar-cadastro", { headers, data: { code: registrationCode(process.env.PORTFOLIO_TEST_DATA_DIR, email) } })).status()).toBe(201);
    }
    db = new DatabaseSync(path.join(process.env.PORTFOLIO_TEST_DATA_DIR, "portfolio.sqlite"));
    db.exec("PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");
    const target = db.prepare("SELECT id,email FROM users WHERE email='editar-ui@example.invalid'").get();
    const admin = db.prepare("SELECT id,email FROM users WHERE email='operador-edicao-ui@example.invalid'").get();
    db.prepare("INSERT INTO user_access(user_id,role) VALUES(?,'admin')").run(admin.id);
    await page.goto(`/administracao?tab=usuarios&q=${encodeURIComponent("Conta de edição")}`);
    const opener = page.getByRole("button", { name: "Editar conta", exact: true });
    const dialog = page.getByRole("dialog", { name: "Editar conta", exact: true });
    const save = dialog.getByRole("button", { name: "Salvar alterações", exact: true });
    let calls = 0;
    page.on("request", request => { if (request.url().endsWith("/api/portal/editar-conta")) calls++; });
    await opener.click();
    await expect(dialog.getByLabel("Nome completo", { exact: true })).toHaveValue("Conta de edição");
    await expect(dialog.getByLabel("Email da conta", { exact: true })).toHaveValue(target.email);
    await expect(save).toBeDisabled();
    await dialog.getByLabel("Nome completo", { exact: true }).fill("Alteração cancelada");
    await dialog.getByRole("button", { name: "Cancelar", exact: true }).click();
    await expect(dialog).not.toBeVisible();
    await expect(opener).toBeFocused();
    expect(calls).toBe(0);
    await opener.click();
    await expect(dialog.getByLabel("Nome completo", { exact: true })).toHaveValue("Conta de edição");
    await page.keyboard.press("Escape");
    await expect(dialog).not.toBeVisible();
    expect(calls).toBe(0);

    await opener.click();
    await dialog.getByLabel("Nome completo", { exact: true }).fill("Conta de edição São José");
    await save.click();
    await expect(page.getByRole("status")).toContainText("Conta de edição São José foi atualizada");
    await expect(page.locator(".admin-user h3")).toHaveText("Conta de edição São José");
    expect((await targetContext.request.post("/api/auth/perfil", { headers, data: { name: "Conta de edição São José" } })).status()).toBe(200); // Uma edição só de nome mantém o acesso.

    await opener.click();
    await dialog.getByLabel("Email da conta", { exact: true }).fill(admin.email);
    await save.click();
    await expect(dialog.getByRole("alert")).toContainText("Este email já está em uso");
    expect(db.prepare("SELECT email FROM users WHERE id=?").get(target.id).email).toBe(target.email);
    await expect(save).toBeEnabled();
    await dialog.getByLabel("Email da conta", { exact: true }).fill(target.email);
    await expect(dialog.getByRole("alert")).toHaveCount(0);
    await expect(save).toBeDisabled();
    await dialog.getByRole("button", { name: "Cancelar", exact: true }).click();
    await expect(dialog).not.toBeVisible();
    await opener.click();
    db.prepare("UPDATE users SET name=? WHERE id=?").run("Conta de edição Atualizada", target.id); // Simula uma alteração concorrente após abrir a edição.
    await dialog.getByLabel("Nome completo", { exact: true }).fill("Sobrescrita antiga");
    await save.click();
    await expect(dialog.getByRole("alert")).toContainText("A conta foi alterada");
    expect(db.prepare("SELECT name FROM users WHERE id=?").get(target.id).name).toBe("Conta de edição Atualizada");
    await dialog.getByRole("button", { name: "Recarregar dados", exact: true }).click();
    await expect(page.locator(".admin-user h3")).toHaveText("Conta de edição Atualizada");

    await page.setViewportSize({ width: 390, height: 844 });
    await opener.click();
    await expect(dialog).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    const bounds = await dialog.boundingBox();
    expect(bounds.x).toBeGreaterThanOrEqual(0);
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(390);
    mkdirSync("test-results", { recursive: true });
    await page.screenshot({ path: "test-results/edicao-conta-mobile.png" });
    await dialog.getByLabel("Nome completo", { exact: true }).fill("Conta de edição Cláudia");
    await dialog.getByLabel("Email da conta", { exact: true }).fill("editar-novo-ui@example.invalid");
    await dialog.getByRole("combobox", { name: "Perfil de acesso", exact: true }).selectOption("cliente");
    await save.click();
    await expect(page.getByRole("status")).toContainText("Será necessário entrar novamente nessa conta");
    await expect(page.locator(".admin-user h3")).toHaveText("Conta de edição Cláudia");
    await expect(page.locator(".admin-user-identity")).toContainText("editar-novo-ui@example.invalid");
    await expect(page.locator(".admin-user-top .admin-badge")).toHaveText("Cliente Plataforma de Privacidade");
    await expect(page.locator(".admin-user-meta")).toContainText("Sem confirmação registrada");
    expect((await targetContext.request.post("/api/auth/perfil", { headers, data: { name: "Sessão antiga" } })).status()).toBe(401);
    expect((await targetContext.request.post("/api/auth/login", { headers, data: { email: target.email, password } })).status()).toBe(401);
    expect((await targetContext.request.post("/api/auth/login", { headers, data: { email: "editar-novo-ui@example.invalid", password } })).status()).toBe(200);
    await page.reload();
    await expect(page.locator(".admin-user-identity")).toContainText("editar-novo-ui@example.invalid");

    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto(`/administracao?tab=usuarios&q=${admin.email}`);
    await opener.click();
    await expect(dialog.getByRole("combobox", { name: "Perfil de acesso", exact: true })).toHaveValue("admin");
    await expect(dialog.getByRole("combobox", { name: "Perfil de acesso", exact: true })).toBeDisabled();
    await dialog.getByLabel("Nome completo", { exact: true }).fill("Administrador editado");
    await dialog.getByLabel("Email da conta", { exact: true }).fill("admin-editado-ui@example.invalid");
    await save.click();
    await expect(page).toHaveURL(/\/login$/);
    await page.getByLabel("E-mail", { exact: true }).fill("admin-editado-ui@example.invalid");
    await page.getByLabel("Senha", { exact: true }).fill(password);
    await page.getByRole("button", { name: "Entrar", exact: true }).click();
    await expect(page).toHaveURL(/\/minha-conta$/);
    await expect(page.getByText("PAINEL DO ADMINISTRADOR", { exact: true })).toBeVisible();
    await page.goto("/administracao?tab=usuarios&q=admin-editado-ui@example.invalid");
    await expect(page.locator(".admin-user h3")).toHaveText("Administrador editado");
    await expect(page.locator(".admin-user-top .admin-badge")).toHaveText("Administrador");
  } finally { db?.close(); await targetContext.close(); }
});

test("páginas públicas, imagens, links e menu responsivo",async({page})=>{
  const errors=[];page.on("pageerror",error=>errors.push(error.message));
  const paths=["/","/consultoria-em-privacidade","/avaliacao-de-terceiros","/hub-educacional","/auditorias-e-avaliacoes","/newsletter","/sobre","/contato","/politica-de-privacidade","/termos-de-uso"];
  for(const pathname of paths){
    const response=await page.goto(pathname);expect(response.status()).toBe(200);
    await expect(page.locator("h1")).toHaveCount(1);
    await expect(page.locator("body")).not.toContainText(/\bBlog\b/);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    expect(await page.evaluate(()=>[...document.images].every(image=>image.complete&&image.naturalWidth>0))).toBe(true);
    const missing=await page.locator('a[href^="#"]').evaluateAll(links=>links.map(link=>link.getAttribute("href")).filter(href=>href!=="#"&&!document.getElementById(href.slice(1))));
    expect(missing).toEqual([]);
  }
  mkdirSync(".data",{recursive:true});
  await page.goto("/");await page.screenshot({path:".data/home-desktop.png",fullPage:true,caret:"initial"});
  await page.setViewportSize({width:390,height:844});
  for(const pathname of paths){await page.goto(pathname);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
  await page.goto("/");
  await page.getByRole("button",{name:"Abrir menu"}).click();
  await expect(page.getByRole("button",{name:"Fechar menu"})).toHaveAttribute("aria-expanded","true");
  await page.getByRole("navigation",{name:"Navegação principal"}).getByRole("link",{name:"Hub Educacional"}).click();
  await expect(page).toHaveURL(/hub-educacional/);
  await expect(page.getByRole("button",{name:"Abrir menu"})).toHaveAttribute("aria-expanded","false");
  await page.goto("/");await page.screenshot({path:".data/home-mobile.png",fullPage:true,caret:"initial"});
  expect(errors).toEqual([]);
  expect((await page.goto("/pagina-inexistente")).status()).toBe(404);
});

test("contato registra protocolo e mantém interesse do link",async({page})=>{
  await page.goto("/contato?interesse=treinamento");
  const form=page.getByRole("form",{name:"Solicitação de proposta"});
  await expect(form.getByLabel("Como podemos ajudar?")).toHaveValue("treinamento");
  await form.getByLabel("Nome completo").fill("Teste automatizado");
  await form.getByLabel("E-mail",{exact:false}).fill("interface@example.invalid");
  await form.getByLabel("Sua mensagem").fill("Teste automatizado local do formulário de proposta.");
  await form.getByRole("checkbox").check();
  await form.getByRole("button",{name:"Enviar solicitação"}).click();
  await expect(form.getByRole("status")).toContainText("PORTFOLIO-");
  await expect(form.getByRole("status")).toContainText("ficou registrada");
  await expect(form.getByRole("heading", { name: "Obrigado por conversar com a gente!" })).toBeVisible();
  await expect(form.getByRole("button", { name: "Enviar solicitação" })).toHaveCount(0);
  const whatsapp = form.getByRole("link", { name: "Continuar pelo WhatsApp" });
  await expect(whatsapp).toHaveAttribute("href", /^https:\/\/wa\.me\/5511999999999\?text=/);
  expect(decodeURIComponent(await whatsapp.getAttribute("href"))).toContain("PORTFOLIO-");
  await expect(whatsapp).toHaveAttribute("target", "_blank");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await form.getByRole("link", { name: "Voltar à página inicial" }).click();
  await expect(page).toHaveURL("/");
  // Alterar cabeçalhos de IP não deve liberar um segundo envio.
  const forged = await page.request.post("/api/contato", {
    headers: { Origin: "http://127.0.0.1:3100", "X-Forwarded-For": "198.51.100.99" },
    data: { name: "Teste repetido", email: "outro@example.invalid", interest: "treinamento", message: "Tentativa durante o intervalo do formulário.", consent: true, website: "" },
  });
  expect(forged.status()).toBe(429);
  expect(Number(forged.headers()["retry-after"])).toBeGreaterThan(0);
  await page.goto("/contato?interesse=treinamento");
  await form.getByLabel("Nome completo").fill("Teste repetido");
  await form.getByLabel("E-mail", { exact: false }).fill("outro@example.invalid");
  await form.getByLabel("Sua mensagem").fill("Tentativa durante o intervalo do formulário.");
  await form.getByRole("checkbox").check();
  await form.getByRole("button", { name: "Enviar solicitação" }).click();
  await expect(form.getByRole("alert")).toContainText("5 minutos");
  await expect(form.getByRole("button", { name: /^Aguarde \d+:\d{2}$/ })).toBeDisabled();
});

test("newsletter: inscrição, confirmação explícita e cancelamento pela interface",async({page})=>{
  await page.goto("/newsletter");
  const form=page.getByRole("form",{name:"Assinar newsletter"});
  await form.getByLabel("Seu nome").fill("Teste interface");
  await form.getByLabel("Seu e-mail").fill("newsletter-ui@example.invalid");
  await form.getByRole("checkbox").check();
  await form.getByRole("button",{name:"Quero receber"}).click();
  await expect(form.getByRole("status")).toContainText("modo local");
  const directory=process.env.PORTFOLIO_TEST_DATA_DIR;
  const files=readdirSync(path.join(directory,"outbox")).map(file=>readFileSync(path.join(directory,"outbox",file),"utf8").replace(/=\r?\n/g,"").replace(/=([0-9A-F]{2})/gi,(_,hex)=>String.fromCharCode(parseInt(hex,16))));
  const message=files.find(content=>content.includes("newsletter-ui@example.invalid"));
  const confirm=message.match(/http:\/\/127\.0\.0\.1:3100\/newsletter\/confirmar\?token=[\w-]{43}/)[0];
  const cancel=message.match(/http:\/\/127\.0\.0\.1:3100\/newsletter\/cancelar\?token=[\w-]{43}/)[0];
  const database=new DatabaseSync(path.join(directory,"portfolio.sqlite"),{readOnly:true});
  const status=()=>database.prepare("SELECT status FROM subscribers WHERE email='newsletter-ui@example.invalid'").get().status;
  try{
    await page.goto(confirm);expect(status()).toBe("pending");
    await expect(page.getByRole("button",{name:"Confirmar minha assinatura"})).toBeEnabled();
    await page.getByRole("button",{name:"Confirmar minha assinatura"}).click();
    await expect(page.getByRole("heading",{name:"Assinatura confirmada."})).toBeVisible();expect(status()).toBe("subscribed");
    await page.goto(cancel);expect(status()).toBe("subscribed");
    await page.getByRole("button",{name:"Confirmar cancelamento"}).click();
    await expect(page.getByRole("heading",{name:"Assinatura cancelada."})).toBeVisible();expect(status()).toBe("unsubscribed");
  }finally{database.close();}
});

test("avaliação em etapas, relatório, CSV, PDF e evidências privadas",async({page,request})=>{
  await page.goto("/avaliacao-de-terceiros");
  await page.getByLabel("Empresa avaliada",{exact:false}).fill("Empresa de teste UI");
  await page.getByLabel("Responsável pelas respostas",{exact:false}).fill("Responsável de teste");
  await page.getByLabel("E-mail do responsável",{exact:false}).fill("assessment-ui@example.invalid");
  await page.getByLabel("Setor de atuação").selectOption("Tecnologia");
  await page.getByRole("button",{name:"Continuar"}).click();
  for(let index=1;index<=6;index++)await page.locator(`input[name="security-${index}"][value="yes"]`).check();
  await page.getByRole("button",{name:"Continuar"}).click();
  for(let index=1;index<=6;index++)await page.locator(`input[name="privacy-${index}"][value="partial"]`).check();
  await page.getByRole("button",{name:"Continuar"}).click();
  await page.locator(".assessment-review").getByRole("checkbox").check();
  await page.getByRole("button",{name:"Gerar meu relatório"}).click();
  await expect(page).toHaveURL(/\/relatorio\/[\w-]+#[\w-]+/);
  await expect(page.getByRole("heading",{name:"Security Score",exact:true})).toBeVisible();
  const values=await page.locator(".report-score-value").allTextContents();expect(values).toEqual(["75/100","100/100","50/100"]);
  const privateUrl=page.url(),id=new URL(privateUrl).pathname.split("/").pop();
  expect((await request.get(`/api/avaliacoes/${id}`)).status()).toBe(404);
  await page.reload();await expect(page.getByRole("heading",{name:"Security Score",exact:true})).toBeVisible();
  const csvPromise=page.waitForEvent("download");await page.getByRole("button",{name:"Exportar plano CSV"}).click();const csv=await csvPromise;expect(csv.suggestedFilename()).toMatch(/\.csv$/);
  const text=readFileSync(await csv.path(),"utf8");expect(text).toContain("Responsável");expect(text).toContain("Empresa de teste UI");
  await page.getByLabel("Arquivo de evidência").setInputFiles({name:"evidencia.pdf",mimeType:"application/pdf",buffer:Buffer.from("%PDF-1.4\nDocumento fictício para teste\n%%EOF")});
  await page.getByRole("button",{name:"Anexar evidência"}).click();
  await expect(page.locator(".report-evidence-list")).toContainText("evidencia.pdf");
  const filePromise=page.waitForEvent("download");await page.getByRole("button",{name:"Baixar",exact:true}).click();expect((await filePromise).suggestedFilename()).toBe("evidencia.pdf");
  await page.getByRole("button",{name:"Excluir",exact:true}).click();await page.getByRole("button",{name:"Confirmar exclusão"}).click();await expect(page.locator(".report-empty")).toContainText("Nenhuma evidência");
  await page.screenshot({path:".data/assessment-report.png",fullPage:true,caret:"initial"});
  await page.emulateMedia({media:"print"});await page.pdf({path:".data/assessment-report-test.pdf",format:"A4",printBackground:true});
  await page.emulateMedia({media:"screen"});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.goto(new URL(privateUrl).pathname);await expect(page.getByRole("main").getByRole("alert")).toContainText("link privado completo");
});
test("carrossel de serviços avança, pausa e adapta ao celular", async ({ page }) => {
  await page.clock.install();
  await page.goto("/");
  const carousel = page.getByRole("region", { name: "Serviços disponíveis" });
  const highlight = page.getByRole("region", { name: "Serviços em destaque" });
  await expect(highlight.locator('.services-carousel__slide:not([inert])')).toHaveCount(1);
  await expect(page.getByText("04 frentes integradas", { exact: true })).toHaveCount(0);
  await expect(carousel.locator('.services-carousel__track')).toHaveAttribute("aria-live", "off");
  await expect(carousel.getByRole("button", { name: /Pausar|Iniciar carrossel/ })).toHaveCount(0);
  await page.clock.runFor(3100);
  await expect(highlight.locator('[aria-current="true"]')).toHaveAttribute("aria-label", "Mostrar serviços a partir do 2");
  await expect.poll(async () => {
    const viewport = await highlight.boundingBox();
    const slide = await highlight.locator('.services-carousel__slide:not([inert])').boundingBox();
    return Math.abs(viewport.width - slide.width) < 2 && Math.abs(viewport.x - slide.x) < 2;
  }).toBe(true);
  await expect(carousel.locator('[aria-current="true"]')).toHaveAttribute("aria-label", "Mostrar serviços a partir do 2");
  await carousel.hover();
  await page.clock.runFor(10000);
  await expect(carousel.locator('[aria-current="true"]')).toHaveAttribute("aria-label", "Mostrar serviços a partir do 2");
  await carousel.getByRole("button", { name: "Mostrar serviços a partir do 3" }).click();
  await expect(carousel.getByRole("link", { name: /Conhecer os escopos/ })).toBeVisible();
  await expect(carousel.locator('.services-carousel__slide:not([inert])')).toHaveCount(2);
  await page.mouse.move(0, 0);
  await page.clock.runFor(3100);
  await expect(carousel.locator('[aria-current="true"]')).toHaveAttribute("aria-label", "Mostrar serviços a partir do 1");
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(carousel.locator('.services-carousel__slide:not([inert])')).toHaveCount(1);
  await carousel.getByRole("button", { name: "Mostrar serviços a partir do 4" }).click();
  await expect(carousel.locator('[aria-current="true"]')).toHaveAttribute("aria-label", "Mostrar serviços a partir do 4");
  await expect(carousel.getByRole("link", { name: /Conhecer os escopos/ })).toHaveAttribute("href", "/auditorias-e-avaliacoes");
  await page.clock.runFor(800);
  await expect.poll(async () => {
    const bounds = await carousel.getByRole("link", { name: /Conhecer os escopos/ }).boundingBox();
    return bounds.x >= 0 && bounds.x + bounds.width <= 390;
  }).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.reload();
  await expect(carousel.locator('.services-carousel__track')).toHaveAttribute("aria-live", "polite");
  await page.clock.runFor(11000);
  await expect(carousel.locator('[aria-current="true"]')).toHaveAttribute("aria-label", "Mostrar serviços a partir do 1");
});

test("carrossel permite arrastar sem abrir links e navegar pelo teclado", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");
  const carousel = page.getByRole("region", { name: "Serviços em destaque" });
  const viewport = carousel.locator('.services-carousel__viewport');
  await expect(carousel.locator('.services-carousel__track')).toHaveAttribute('aria-live', 'polite');
  await expect(page.getByRole('button', { name: /Serviço anterior|Próximo serviço|Pausar carrossel/ })).toHaveCount(0);
  await carousel.scrollIntoViewIfNeeded();
  const link = carousel.locator('.services-carousel__slide:not([inert]) a');
  const box = await link.boundingBox();
  await page.mouse.move(box.x + box.width * .8, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width * .2, box.y + box.height / 2, { steps: 12 });
  await page.mouse.up();
  await expect(page).toHaveURL(/\/$/);
  await expect(carousel.locator('[aria-current="true"]')).toHaveAttribute('aria-label', 'Mostrar serviços a partir do 2');
  await viewport.focus();
  await page.keyboard.press('ArrowRight');
  await expect(carousel.locator('[aria-current="true"]')).toHaveAttribute('aria-label', 'Mostrar serviços a partir do 3');
  await page.keyboard.press('ArrowLeft');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(carousel.locator('[aria-current="true"]')).toHaveAttribute('aria-label', 'Mostrar serviços a partir do 1');
  await viewport.dispatchEvent('pointerdown', { pointerId: 7, pointerType: 'touch', isPrimary: true, button: 0, clientX: 300, clientY: 200 });
  // A vertical gesture must remain available for scrolling the page.
  await viewport.dispatchEvent('pointermove', { pointerId: 7, pointerType: 'touch', isPrimary: true, clientX: 295, clientY: 280 });
  await expect(carousel.locator('[aria-current="true"]')).toHaveAttribute('aria-label', 'Mostrar serviços a partir do 1');
  await expect(viewport).not.toHaveClass(/is-dragging/);
  await viewport.scrollIntoViewIfNeeded();
  const touchBox = await viewport.boundingBox();
  const touchX = touchBox.x + touchBox.width * .8;
  const touchY = touchBox.y + 70;
  const cdp = await page.context().newCDPSession(page);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: touchX, y: touchY }] });
  for (let step = 1; step <= 10; step++) {
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: touchX - step * 15, y: touchY }] });
  }
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await expect(carousel.locator('[aria-current="true"]')).toHaveAttribute('aria-label', 'Mostrar serviços a partir do 2');
  await carousel.getByRole('button', { name: 'Mostrar serviços a partir do 1' }).click();
  await link.click();
  await expect(page).toHaveURL(/consultoria-em-privacidade/);
});
