import test, { after } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import { registrationCode } from "./email-helper.mjs";

process.env.NODE_ENV = "development";
process.env.SITE_URL = "http://localhost";
delete process.env.PORTFOLIO_TRUST_PROXY;
for (const key of ["SMTP_HOST", "SMTP_USER", "SMTP_PASS", "MAIL_FROM"]) delete process.env[key];
const directory = mkdtempSync(path.join(os.tmpdir(), "portfolio-portal-test-"));
process.env.PORTFOLIO_DATA_DIR = directory;
const core = await import("../lib/server/core.js");
const auth = await import("../lib/server/auth.js");
const portal = await import("../lib/server/portal.js");
const { assessmentQuestions } = await import("../lib/assessment.js");
const req = (data, cookie = "", method = "POST", origin = "http://localhost") => new Request("http://localhost/api/test", { method, headers: { "Content-Type": "application/json", Origin: origin, Cookie: cookie }, ...(method !== "GET" ? { body: JSON.stringify(data) } : {}) });
const call = (fn, data, cookie, params = {}) => core.handled(fn)(req(data, cookie), { params: Promise.resolve(params) });
const mutation = (action, data, cookie) => call(portal.portalMutation, data, cookie, { action });
const assessment = { company: "Empresa de teste", name: "Responsável", email: "same@example.invalid", sector: "Tecnologia", consent: true, answers: Object.fromEntries(assessmentQuestions.map(item => [item.id, "no"])) };
async function account(name) {
  const pending = await call(auth.register, { name, email: `${name}@example.invalid`, password: "frase longa para teste", terms: true, role: "admin" });
  assert.equal(pending.status, 202);
  const response = await call(auth.confirmRegistration, { code: registrationCode(directory, `${name}@example.invalid`) }, pending.headers.get("set-cookie").split(";")[0]);
  assert.equal(response.status, 201);
  const cookie = response.headers.get("set-cookie").split(";")[0];
  return { cookie, user: auth.sessionUser(cookie.split("=")[1]) };
}
after(() => {
  const key = Symbol.for("privacy-platform.sqlite"); globalThis[key]?.close(); delete globalThis[key];
  if (path.dirname(directory) === path.resolve(os.tmpdir()) && path.basename(directory).startsWith("portfolio-portal-test-")) rmSync(directory, { recursive: true, force: true });
});

test("perfis, isolamento de avaliações, plano de ação e atendimento", async () => {
  const first = await account("primeiro"), second = await account("segundo"), admin = await account("operador");
  assert.equal(first.user.role, "usuario"); // input cannot grant privileges
  portal.portalDatabase().prepare("INSERT INTO user_access(user_id,role) VALUES(?,'admin')").run(admin.user.id);
  const result = await call(core.createAssessment, { ...assessment, userId: second.user.id }, first.cookie);
  assert.equal(result.status, 201);
  const report = await result.json();
  assert.equal(report.token, undefined);
  assert.equal(portal.portalData(first.user).assessments.length, 1);
  assert.equal(portal.portalData(second.user).assessments.length, 0);
  assert.equal((await call(core.getAssessment, {}, first.cookie, { id: report.id })).status, 200);
  assert.equal((await call(core.getAssessment, {}, second.cookie, { id: report.id })).status, 404);
  assert.equal((await call(core.getAssessment, {}, "", { id: report.id })).status, 404);
  const evidenceId = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa";
  core.db().prepare("INSERT INTO evidences(id,assessment_id,name,mime,size,category,content,created_at) VALUES(?,?,?,?,?,?,?,?)").run(evidenceId, report.id, "prova.pdf", "application/pdf", 5, "other", Buffer.from("%PDF-"), Date.now());
  assert.equal((await call(core.downloadEvidence, {}, first.cookie, { id: report.id, evidenceId })).status, 200);
  assert.equal((await call(core.downloadEvidence, {}, second.cookie, { id: report.id, evidenceId })).status, 404);
  assert.equal((await call(core.deleteEvidence, {}, second.cookie, { id: report.id, evidenceId })).status, 404);
  assert.equal((await mutation("acesso", { userId: first.user.id, role: "cliente" }, first.cookie)).status, 403);
  assert.equal((await mutation("solicitacao", { subject: "Ajuda", message: "Preciso de suporte" }, first.cookie)).status, 403);
  assert.equal((await mutation("acesso", { userId: first.user.id, role: "cliente" }, admin.cookie)).status, 200);
  assert.equal((await mutation("acesso", { userId: second.user.id, role: "admin" }, admin.cookie)).status, 400);
  assert.equal((await mutation("acesso", { userId: second.user.id, role: "cliente" }, admin.cookie)).status, 200);
  assert.equal((await mutation("acao", { assessmentId: report.id }, first.cookie)).status, 401);
  for (const entry of [first, second]) entry.cookie = (await call(auth.login, { email: entry.user.email, password: "frase longa para teste" })).headers.get("set-cookie").split(";")[0];
  const action = { assessmentId: report.id, actionId: "security-1", assignee: "Equipe TI", dueDate: "2027-01-15", status: "andamento" };
  assert.equal((await mutation("acao", action, first.cookie)).status, 200);
  assert.equal((await mutation("acao", action, second.cookie)).status, 404);
  assert.equal((await mutation("acao", { ...action, actionId: "inexistente" }, first.cookie)).status, 400);
  assert.equal((await mutation("acao", { ...action, dueDate: "2027-02-30" }, first.cookie)).status, 400);
  assert.equal((await mutation("solicitacao", { subject: "Ajuda", message: "Preciso de suporte", userId: second.user.id }, first.cookie)).status, 200);
  const firstUser = auth.sessionUser(first.cookie.split("=")[1]);
  const data = portal.portalData(firstUser);
  assert.equal(data.progress[0].assignee, "Equipe TI");
  assert.equal(data.requests[0].user_id, first.user.id);
  assert.equal(portal.portalData(auth.sessionUser(second.cookie.split("=")[1])).requests.length, 0);
  assert.equal((await mutation("resposta", { id: data.requests[0].id, reply: "Vamos acompanhar", status: "andamento" }, first.cookie)).status, 403);
  assert.equal((await mutation("resposta", { id: data.requests[0].id, reply: "Vamos acompanhar", status: "andamento" }, admin.cookie)).status, 200);
  assert.equal((await mutation("servico", { userId: first.user.id, title: "Consultoria", description: "Diagnóstico inicial", status: "planejado", dueDate: "" }, admin.cookie)).status, 200);
  assert.equal(portal.portalData(firstUser).services.length, 1);
  assert.equal(portal.portalData(auth.sessionUser(second.cookie.split("=")[1])).services.length, 0);
  assert.equal(portal.portalData(firstUser).requests[0].reply, "Vamos acompanhar");
  const unread = portal.portalData(firstUser).requests[0];
  assert.equal(unread.unread, true);
  assert.match(unread.replyVersion, /^[a-f0-9]{64}$/);
  assert.equal((await mutation("leitura", { id: unread.id, version: unread.replyVersion }, second.cookie)).status, 404);
  assert.equal((await mutation("leitura", { id: unread.id, version: "f".repeat(64) }, first.cookie)).status, 409);
  assert.equal(portal.portalData(firstUser).requests[0].unread, true);
  assert.equal((await mutation("leitura", { id: unread.id, version: unread.replyVersion, userId: second.user.id }, first.cookie)).status, 200);
  assert.equal(portal.portalData(firstUser).requests[0].unread, false);
  assert.equal(portal.portalDatabase().prepare("SELECT user_id,read_at FROM request_reads WHERE request_id=?").get(unread.id).user_id, first.user.id);
  assert.equal((await mutation("leitura", { id: unread.id, version: unread.replyVersion }, first.cookie)).status, 200); // Idempotente.
  assert.equal((await mutation("resposta", { id: unread.id, reply: "Nova orientação da equipe", status: "andamento" }, admin.cookie)).status, 200);
  const revised = portal.portalData(firstUser).requests[0];
  assert.equal(revised.unread, true);
  assert.notEqual(revised.replyVersion, unread.replyVersion);
  assert.equal((await mutation("leitura", { id: revised.id, version: unread.replyVersion }, first.cookie)).status, 409);
  assert.equal(portal.portalData(firstUser).requests[0].unread, true);
  assert.equal((await mutation("leitura", { id: revised.id, version: revised.replyVersion }, first.cookie)).status, 200);
  const badOrigin = await core.handled(portal.portalMutation)(req(action, first.cookie, "POST", "https://evil.invalid"), { params: Promise.resolve({ action: "acao" }) });
  assert.equal(badOrigin.status, 403);
  assert.equal((await mutation("acesso", { userId: first.user.id, role: "usuario" }, admin.cookie)).status, 200);
  assert.equal((await mutation("acao", action, first.cookie)).status, 401);
  first.cookie = (await call(auth.login, { email: first.user.email, password: "frase longa para teste" })).headers.get("set-cookie").split(";")[0];
  assert.equal((await mutation("acao", action, first.cookie)).status, 403);
  assert.equal((await mutation("leitura", { id: revised.id, version: revised.replyVersion }, first.cookie)).status, 403);
  assert.equal((await mutation("leitura", { id: revised.id, version: revised.replyVersion }, "")).status, 401);
  assert.equal((await mutation("acao", action, "")).status, 401);
});

test("administração: pesquisa, filtros, paginação e isolamento dos registros de email", () => {
  const db = portal.portalDatabase();
  const admin = { ...db.prepare("SELECT * FROM users WHERE name='operador'").get(), role: "admin" };
  const first = { ...db.prepare("SELECT * FROM users WHERE name='primeiro'").get(), role: "usuario" };
  assert.throws(() => portal.adminData(first), /Acesso restrito/);
  assert.throws(() => portal.adminSummary(first), /Acesso restrito/);
  assert.equal(portal.portalData(first).emails, undefined);
  const users = portal.adminData(admin, { tab: "usuarios", q: "PRIMEIRO", role: "usuario", status: "ativas" });
  assert.equal(users.users.length, 1);
  assert.equal(users.users[0].id, first.id);
  assert.equal(users.users[0].open_requests, 1);
  assert.ok(users.users[0].verified_at);
  assert.equal(portal.adminData(admin, { tab: "usuarios", q: "' OR 1=1 --" }).users.length, 0);
  assert.equal(portal.adminData(admin, { tab: "usuarios", q: "%" }).users.length, 0);
  assert.equal(portal.adminData(admin, { tab: "usuarios", role: "admin" }).users[0].id, admin.id);
  const requests = portal.adminData(admin, { tab: "solicitacoes", userId: first.id, status: "andamento" });
  assert.equal(requests.requests.length, 1);
  assert.equal(portal.adminData(admin, { tab: "solicitacoes", status: "concluida" }).requests.length, 0);
  assert.equal(portal.adminData(admin, { tab: "emails", category: "cadastro", status: "local", q: "primeiro@" }).emails.length, 1);
  const now = Date.now();
  for (let i = 0; i < 30; i++) db.prepare("INSERT INTO email_events(id,created_at,completed_at,recipient,subject,category,status,smtp_code) VALUES(?,?,?,?,?,'teste','accepted',250)")
    .run(`paginated-${i}`, now + i, now + i, "paginacao@example.invalid", "Teste de paginação");
  db.prepare("INSERT INTO email_events(id,created_at,recipient,subject,category,status) VALUES('antigo',?,?,'Antigo','teste','failed')").run(now - 8 * 86_400_000, "antigo@example.invalid");
  const emails = portal.adminData(admin, { tab: "emails", q: "paginacao@", status: "accepted", period: "7", page: "2" });
  assert.equal(emails.emails.length, 5);
  assert.equal(emails.pagination.emails.total, 30);
  assert.equal(emails.pagination.emails.page, 2);
  assert.equal(portal.adminData(admin, { tab: "emails", status: "failed", period: "7" }).emails.length, 0);
  assert.equal(portal.adminData(admin, { tab: "emails", status: "failed" }).emails.length, 1);
  assert.equal(portal.adminSummary(admin).acceptedEmails, 30);
  assert.equal(portal.adminSummary(admin).openRequests, 1);
});
