import Link from "next/link";
import LegalIdentity from "@/components/LegalIdentity";
import { PageHero } from "@/components/Editorial";

export const metadata = {title:"Política de Privacidade",description:"Informações sobre o tratamento de dados nos formulários, na newsletter e na avaliação de terceiros da Plataforma de Privacidade."};
const sections = [["escopo","Sobre este documento"],["dados","Dados e finalidades"],["assinatura","Newsletter"],["avaliacoes","Avaliações e evidências"],["seguranca","Armazenamento e acesso"],["direitos","Seus direitos"],["cookies","Cookies e links externos"]];
export default function PrivacyPage() {
  return <main id="conteudo"><PageHero eyebrow="Transparência / Privacidade" title="Seus dados merecem clareza." description="Conheça o uso das informações nos recursos disponíveis neste site e os caminhos para entrar em contato sobre seus dados." />
    <section className="section"><div className="shell legal-layout"><nav className="legal-nav" aria-label="Seções da política">{sections.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><article className="legal-content">
      <LegalIdentity />
      <section id="escopo"><h2>1. Sobre este documento</h2><p>Esta página apresenta como os formulários de contato, as contas de usuário, a área de clientes, a assinatura da newsletter e a autoavaliação de terceiros utilizam as informações fornecidas. A marca apresentada é Plataforma de Privacidade. A identificação institucional e o contato sobre privacidade aparecem acima quando configurados pelo responsável.</p><p>Você pode encaminhar dúvidas ou solicitações pelo <Link href="/contato?interesse=dados-pessoais">formulário de contato sobre dados pessoais</Link>.</p></section>
      <section id="dados"><h2>2. Dados e finalidades</h2><ul><li><strong>Contato:</strong> nome, e-mail, empresa e telefone quando informados, serviço de interesse, mensagem, autorização e data do envio. A finalidade é registrar a demanda, responder e preparar uma proposta quando solicitada.</li><li><strong>Contas e atendimento:</strong> nome, email, senha armazenada como derivação criptográfica, confirmação de email, aceite dos termos, sessões, perfil de acesso, solicitações e respostas de atendimento e serviços contratados. Essas informações permitem autenticar o acesso, organizar o trabalho e atender o cliente. Administradores podem corrigir dados e excluir contas; as ações ficam no histórico de segurança.</li><li><strong>Duas etapas:</strong> a chave do aplicativo autenticador é armazenada criptografada. Os códigos de recuperação são armazenados como hashes e cada código pode ser usado uma única vez.</li><li><strong>Newsletter:</strong> e-mail, nome quando informado, registro da autorização, confirmação e cancelamento. A finalidade é administrar a assinatura e o recebimento das edições.</li><li><strong>Avaliação:</strong> empresa, setor, nome e e-mail do responsável, respostas, data, autorização e documentos enviados. A finalidade é gerar o relatório orientativo e disponibilizar os anexos ao titular da conta ou, nas avaliações sem conta, aos portadores do link privado.</li><li><strong>Operação:</strong> registros técnicos de acesso e tentativas podem ser utilizados para manter o serviço e limitar abuso. As informações disponíveis nesses registros dependem também do ambiente de hospedagem.</li></ul><p>Os formulários solicitam autorização específica para a finalidade indicada. Entrar em contato ou responder à avaliação não ativa uma assinatura da newsletter. As bases legais e demais condições de tratamento da operação institucional devem ser consolidadas no texto jurídico definitivo.</p></section>
      <section id="assinatura"><h2>3. Assinatura da newsletter</h2><p>A inscrição permanece pendente até que você abra o link recebido e pressione o botão de confirmação. O link de confirmação expira em 24 horas. A simples abertura da página não ativa a assinatura.</p><p>O cancelamento pode ser feito pelo link recebido por e-mail ou por solicitação no formulário de contato. O cancelamento desativa o recebimento; não exclui automaticamente todos os registros da inscrição. Pedidos de exclusão são tratados separadamente.</p><p>No ambiente local de testes, sem serviço de envio configurado, as mensagens são guardadas na caixa de testes do responsável pelo site e não são enviadas externamente.</p></section>
      <section id="avaliacoes"><h2>4. Avaliações e evidências</h2><p>Avaliações vinculadas a uma conta exigem a sessão de seu titular. Avaliações criadas sem conta exigem o link privado gerado ao concluir o formulário. Nesse caso, quem tiver o link poderá ler o resultado, anexar, baixar e excluir evidências. Compartilhe-o apenas com pessoas autorizadas e evite incluí-lo em materiais públicos.</p><p>São aceitos até cinco documentos PDF, PNG ou JPEG, de até 5 MB cada. Envie apenas materiais que tenha autorização para compartilhar. Remova dados pessoais, segredos, credenciais e outras informações desnecessárias antes do envio.</p><p>As respostas e evidências são armazenadas para disponibilizar a avaliação. O envio dos documentos não representa revisão humana, verificação automática de conformidade ou validação das informações declaradas.</p></section>
      <section id="seguranca"><h2>5. Armazenamento, acesso e conservação</h2><p>Solicitações, assinaturas e avaliações ficam armazenadas no ambiente que executa o site. Os documentos não são disponibilizados em uma pasta pública. O acesso aos registros administrativos exige perfil autorizado e, em produção, autenticação em duas etapas. O responsável pela operação mantém backups criptografados e pode restaurá-los em caso de falha. O período configurado de backups deve corresponder à política de conservação aprovada.</p><p>Quando o envio de e-mail estiver configurado, o provedor escolhido processará os dados necessários para entregar as mensagens. O histórico de envio registra destinatário, assunto, horários, aceite SMTP e diagnósticos de falha, sem guardar senhas ou códigos de autenticação nesse histórico. Contatos que falham podem ser reenviados automaticamente, até seis tentativas. O aceite SMTP não comprova leitura ou chegada à caixa de entrada. A identificação dos provedores e as condições da hospedagem devem constar da versão aprovada. A versão atual não tem integração com plataformas de anúncios ou ferramentas de análise de audiência.</p><p>Não há exclusão automática por prazo nesta versão. Os períodos de conservação, as rotinas de revisão e os critérios de descarte precisam ser definidos pela Plataforma de Privacidade. A exclusão de uma conta pelo administrador remove suas sessões, avaliações, evidências, tarefas, serviços e atendimentos vinculados. Os registros de auditoria, histórico de email, contatos e inscrições na newsletter são tratados separadamente, assim como as cópias de segurança, conforme os critérios de conservação aplicáveis. Solicitações de exclusão podem ser encaminhadas pelo formulário de contato para análise e execução pelo responsável.</p></section>
      <section id="direitos"><h2>6. Solicitações relacionadas aos seus dados</h2><p>A legislação prevê direitos como acesso, correção, informação sobre o tratamento e, conforme o caso, eliminação e revogação do consentimento. A aplicação de cada direito depende do contexto e das obrigações de conservação existentes.</p><p>Use o <Link href="/contato?interesse=dados-pessoais">canal de solicitações sobre dados pessoais</Link>, indicando o e-mail utilizado e o pedido. Poderá ser necessária uma verificação proporcional de identidade antes do atendimento; evite enviar documentos pessoais no primeiro contato.</p><p>Consulte as orientações oficiais da <a href="https://www.gov.br/anpd/pt-br/assuntos/titular-de-dados-1/direito-dos-titulares" target="_blank" rel="noopener noreferrer">ANPD sobre direitos dos titulares</a> e o texto da <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" target="_blank" rel="noopener noreferrer">Lei Geral de Proteção de Dados</a>.</p></section>
      <section id="cookies"><h2>7. Cookies e links externos</h2><p>A aplicação não utiliza cookies de publicidade, pixels de rastreamento ou analytics nesta versão. São utilizados cookies essenciais de sessão, confirmação de cadastro e confirmação de duas etapas para autenticar contas e limitar a utilização dos códigos. Eles são protegidos contra leitura por scripts e utilizam conexão segura em produção. Não há cookies de marketing. Recursos técnicos do ambiente de desenvolvimento e da hospedagem podem variar conforme a configuração.</p><p>Links para WhatsApp, LinkedIn ou edições hospedadas em outros serviços levam a ambientes sujeitos às políticas dos respectivos provedores. Se novas ferramentas de medição, cookies ou integrações forem adicionadas, esta política e os controles de escolha deverão ser atualizados.</p></section>
    </article></div></section>
  </main>;
}
