import Link from "next/link";
import { PageHero, SectionHeading, ServiceCard, CtaBand, Steps } from "@/components/Editorial";
import { companyValues } from "@/lib/content";
import { getPublicContact } from "@/lib/site";

export const metadata = { title: "Sobre a Plataforma de Privacidade", description: "Conheça a proposta da Plataforma de Privacidade para conectar segurança, privacidade, educação e avaliações às decisões da sua organização." };

export default function AboutPage() {
  const { founder } = getPublicContact();
  return <main id="conteudo"><PageHero eyebrow="Sobre a Plataforma de Privacidade" title="Proteção se constrói com pessoas, processos e decisões." description="Uma proposta que aproxima segurança, privacidade e governança da realidade do negócio, com clareza sobre o que precisa ser feito e como avançar."><p className="page-kicker">Nosso propósito</p><p>Transformar temas complexos em caminhos compreensíveis para proteger informações e apoiar decisões responsáveis.</p><Link className="button button--navy" href="/contato">Conhecer nossas soluções ↗</Link></PageHero>
    <section className="section"><div className="shell split-layout"><div><p className="page-kicker">Quem somos</p><h2>Uma visão integrada para desafios que se conectam.</h2>{founder && <p>Fundadora: <strong>{founder}</strong></p>}</div><div className="content-prose"><p>A Plataforma de Privacidade reúne frentes de consultoria em privacidade, capacitação e avaliações para apoiar organizações na proteção de suas informações. Essas frentes se encontram no dia a dia: um processo precisa de regras claras, pessoas preparadas e formas de verificar se os controles funcionam.</p><p>A proposta é construir esse entendimento junto às equipes. Cada trabalho começa pelo contexto da organização e avança com escopo definido, responsabilidades compartilhadas e entregas que ajudem a orientar a operação.</p></div></div></section>
    <section className="section section--tint"><div className="shell"><SectionHeading eyebrow="Missão e direção" title="Clareza para proteger. Consistência para evoluir." /><div className="card-grid card-grid--two"><ServiceCard title="Nossa missão" description="Apoiar organizações a integrar segurança, privacidade e governança às suas rotinas, tornando riscos, responsabilidades e ações mais compreensíveis para quem precisa decidir e executar." /><ServiceCard title="A transformação que buscamos" description="Organizações em que a proteção das informações seja parte do trabalho cotidiano: dos novos projetos à relação com terceiros, das políticas às escolhas das pessoas e da resposta a incidentes à continuidade do negócio." /></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Nossos valores" title="Princípios que orientam a forma de trabalhar." description="As escolhas de um projeto importam tanto quanto seus documentos." /><div className="card-grid">{companyValues.map((value, index) => <ServiceCard key={value.title} number={String(index + 1).padStart(2, "0")} title={value.title} description={value.description} />)}</div></div></section>
    <section className="section section--navy"><div className="shell"><SectionHeading eyebrow="Nossa abordagem" title="Construir com quem conhece a operação." description="Tecnologia, negócio, segurança e privacidade precisam conversar. Nosso trabalho busca aproximar essas perspectivas e dar visibilidade às decisões." /><Steps items={[{title:"Escuta e contexto",description:"Entender objetivos, dificuldades e o que já funciona antes de propor mudanças."},{title:"Escopo e prioridades",description:"Definir o problema, as entregas esperadas e a participação dos responsáveis."},{title:"Trabalho em conjunto",description:"Construir recomendações e materiais com as áreas para fazerem sentido na operação."},{title:"Continuidade",description:"Organizar próximos passos e responsabilidades para acompanhar as melhorias."}]} /></div></section>
    <CtaBand title="Vamos conhecer o contexto do seu negócio?" description="Conte o que sua organização precisa proteger, compreender ou melhorar. A primeira conversa ajuda a identificar por onde começar." label="Falar com a Plataforma de Privacidade ↗" />
  </main>;
}
