import { operationOverview } from "@/lib/server/operations";
import { adminDate } from "./AdminOverview";
import PortalForm from "./PortalForm";
const actions = { "contact.retry_requested": "Reenvio de contato solicitado", "account.edited": "Conta editada", "account.deleted": "Conta excluída", "account.role_changed": "Perfil alterado", "mfa.activated": "Duas etapas ativadas", "mfa.login": "Login com duas etapas", "mfa.recovery_used": "Código de recuperação utilizado", "mfa.reset_by_operator": "Autenticador redefinido pelo operador", "email.verified": "Email confirmado" };
const statuses = { pending: "Aguardando envio", retry: "Nova tentativa programada", sending: "Envio em andamento", failed: "Tentativas esgotadas" };
export default function AdminOperations({ user }) {
  const { states, queue, audit } = operationOverview(user);
  const healthy = states.worker?.at > Date.now() - 300_000;
  return <>
    <section className="admin-card"><h2>Operação e segurança</h2><div className="admin-operations-grid"><article><h3>Rotinas automáticas</h3><p className={healthy ? "form-status" : "form-error"}>{healthy ? "Processo ativo" : "Sem atividade recente"}</p><p>Última atividade: {adminDate(states.worker?.at)}</p></article><article><h3>Backup criptografado</h3><p>Última cópia: {adminDate(states.backup?.at)}</p><p>{states["backup-error"]?.status === "failed" ? "Falha na última tentativa. Verifique o processo no servidor." : states.backup ? states.backup.mirrored ? "Cópia adicional configurada" : "Cópia local disponível; configure o armazenamento externo." : "Nenhum backup automático registrado."}</p></article></div></section>
    <section className="admin-card"><h2>Contatos aguardando email</h2><p>Até seis tentativas automáticas. O contato permanece registrado mesmo quando o SMTP falha. Os códigos de cadastro e recuperação exigem um novo pedido pelo usuário.</p>{queue.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Ticket</th><th>Status</th><th>Tentativas / próxima tentativa</th></tr></thead><tbody>{queue.map(item => <tr key={item.reference}><td>{item.reference}<small>{adminDate(item.created_at)}</small></td><td>{statuses[item.status] || item.status}<small>{item.last_error_code}</small></td><td>{item.attempts} de 6<small>{item.status === "failed" ? "Revisão pelo responsável necessária" : adminDate(item.next_attempt_at)}</small>{item.status === "failed" && <PortalForm action="reenviar-contato" label={`Tentar novamente: ${item.reference}`} submitLabel="Tentar novamente"><input name="reference" type="hidden" value={item.reference} /></PortalForm>}</td></tr>)}</tbody></table></div> : <p>Nenhum contato aguardando envio.</p>}</section>
    <section className="admin-card"><h2>Histórico de segurança</h2><p>Os 50 eventos mais recentes. As ações de exclusão permanecem neste registro após a remoção da conta.</p>{audit.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Horário</th><th>Responsável</th><th>Ação / conta</th></tr></thead><tbody>{audit.map(item => <tr key={item.id}><td>{adminDate(item.created_at)}</td><td>{item.actor_name}</td><td><span>{actions[item.action] || item.action}</span><small>Conta: {item.target_id}</small></td></tr>)}</tbody></table></div> : <p>Nenhuma ação registrada até o momento.</p>}</section>
  </>;
}
