import Link from "next/link";
import PortalForm from "@/components/PortalForm";
import MemberOverview from "@/components/MemberOverview";
import { assessmentQuestions } from "@/lib/assessment";

const statuses = { pendente: "Pendente", aberta: "Aberta", planejado: "Planejado", andamento: "Em andamento", concluida: "Concluída", concluido: "Concluído" };
const date = value => new Date(value).toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" });

export default function MemberDashboard({ user, data, section = "visao-geral", selectedAssessment = "" }) {
  const { assessments, progress, requests, services, documents } = data;
  const firstAssessment = assessments.length === 0;
  const actions = assessments.flatMap(item => item.actions);
  if (section === "visao-geral") return <MemberOverview user={user} data={data} />;
  return <div className="member-dashboard">
    {section === "avaliacoes" && <section id="avaliacoes" className="portal-section"><div className="account-section-heading"><h2>Minhas avaliações</h2><Link className="button button--navy" href="/avaliacao-de-terceiros#avaliacao">{firstAssessment ? "Fazer minha primeira avaliação" : "Nova avaliação"}</Link></div><p>As avaliações criadas enquanto você está conectado ficam salvas aqui. As notas são baseadas nas respostas e não representam certificação.</p>
      {firstAssessment ? <div className="portal-empty"><strong>Seus resultados ficarão aqui</strong><p>Ao concluir uma avaliação, você poderá consultar as notas e abrir o relatório neste histórico.</p><Link href="/minha-conta#primeiros-passos">Veja como começar →</Link></div> : <div className="portal-table"><table><caption>Histórico de avaliações — compare avaliações da mesma empresa</caption><thead><tr><th>Empresa / data</th><th>Segurança</th><th>Privacidade</th><th>Geral</th><th>Relatório</th></tr></thead><tbody>{assessments.map(item => <tr key={item.id}><td>{item.company}<small>{date(item.createdAt)}</small></td><td>{item.scores.security}/100</td><td>{item.scores.privacy}/100</td><td>{item.scores.overall}/100</td><td><Link href={`/avaliacao-de-terceiros/relatorio/${item.id}`}>Abrir relatório</Link></td></tr>)}</tbody></table></div>}
    </section>}
    {section === "materiais" && <section id="materiais" className="portal-section"><h2>Materiais para começar</h2><p>Um checklist para organizar a autoavaliação com sua equipe.</p><details><summary>Checklist de segurança e privacidade</summary><ul className="portal-checklist">{assessmentQuestions.map(item => <li key={item.id}><strong>{item.title}</strong><p>{item.description}</p></li>)}</ul></details><p><Link href="/api/portal/material">Baixar checklist em CSV</Link> · <Link href="/hub-educacional">Explorar o Hub Educacional</Link></p></section>}
    {section === "plano" && <section id="plano" className="portal-section"><h2>Plano de ação</h2><p>Organize as recomendações das avaliações. Atualizar uma tarefa não altera a nota original; faça uma nova avaliação para medir a evolução.</p>
      {!actions.length && <div className="portal-empty"><strong>{firstAssessment ? "Seu plano começa pela avaliação" : "Nenhuma recomendação gerada"}</strong><p>{firstAssessment ? "Após avaliar uma empresa, você poderá definir responsáveis e prazos para os controles que precisam melhorar." : "Os controles aplicáveis das suas avaliações foram declarados implementados. Faça revisões periódicas para acompanhar a evolução."}</p><Link href={firstAssessment ? "/minha-conta#primeiros-passos" : "/avaliacao-de-terceiros#avaliacao"}>{firstAssessment ? "Veja como começar" : "Fazer nova avaliação"} →</Link></div>}
      {assessments.filter(item => item.actions.length).map(assessment => <details key={assessment.id} className="portal-plan" open={assessment.id === selectedAssessment}><summary>{assessment.company} · {date(assessment.createdAt)} · {assessment.actions.length} ações</summary>{assessment.actions.map(action => {
        const saved = progress.find(item => item.assessment_id === assessment.id && item.action_id === action.id);
        return <article key={action.id} id={`acao-${assessment.id}-${action.id}`} className="portal-task"><h3>{action.title}</h3><p>Prioridade {action.priority}</p><p>{action.recommendation}</p><PortalForm action="acao" label={`Salvar ação: ${action.title}`}><input type="hidden" name="assessmentId" value={assessment.id} /><input type="hidden" name="actionId" value={action.id} /><div className="portal-fields"><label className="form-field">Responsável<input name="assignee" defaultValue={saved?.assignee || ""} maxLength={120} /></label><label className="form-field">Prazo<input name="dueDate" type="date" defaultValue={saved?.due_date || ""} /></label><label className="form-field">Status<select name="status" defaultValue={saved?.status || "pendente"}><option value="pendente">Pendente</option><option value="andamento">Em andamento</option><option value="concluida">Concluída</option></select></label></div></PortalForm></article>;
      })}</details>)}
    </section>}
    {section === "documentos" && <section id="documentos" className="portal-section"><h2>Documentos e evidências</h2><p>Anexe PDFs e imagens pelo relatório de cada avaliação. Os arquivos ficam restritos à sua conta.</p>{!documents.length ? <div className="portal-empty"><strong>Reúna os documentos da avaliação</strong><p>{firstAssessment ? "Conclua sua primeira avaliação para anexar documentos que apoiem as respostas." : "Abra o relatório de uma avaliação e anexe políticas, procedimentos ou registros na área de evidências."}</p>{firstAssessment ? <Link href="/minha-conta#primeiros-passos">Veja como começar →</Link> : <Link href={`/avaliacao-de-terceiros/relatorio/${assessments[0].id}#evidence-title`}>Anexar ao relatório mais recente →</Link>}</div> : <ul>{documents.map(item => <li key={item.id}><a href={`/api/avaliacoes/${item.assessment_id}/evidencias/${item.id}`}>{item.name}</a> — {item.company}</li>)}</ul>}</section>}
    {section === "servicos" && <section id="servicos" className="portal-section"><h2>Seus serviços</h2>{!services.length ? <div className="portal-empty"><strong>Acompanhe os serviços contratados</strong><p>A equipe Plataforma de Privacidade cadastra aqui o andamento, a descrição e os prazos dos seus serviços. Nenhum serviço foi cadastrado para esta conta.</p><Link href="/minha-conta/atendimento">Falar com a equipe pelo atendimento →</Link></div> : services.map(item => <article className="portal-task" key={item.id}><h3>{item.title}</h3><p className="portal-badge">{statuses[item.status]}</p><p className="portal-text">{item.description}</p>{item.due_date && <p>Prazo: {item.due_date.split("-").reverse().join("/")}</p>}</article>)}</section>}
    {section === "atendimento" && <section id="atendimento" className="portal-section"><h2>Atendimento Plataforma de Privacidade</h2><p>Envie uma solicitação e acompanhe as respostas. Após ler uma nova resposta, marque-a como lida.</p><details className="account-new-request"><summary>Nova solicitação</summary><PortalForm action="solicitacao" label="Enviar solicitação" reset><label className="form-field">Assunto<input name="subject" required maxLength={160} /></label><label className="form-field">Mensagem<textarea name="message" required maxLength={5000} rows={4} /></label></PortalForm></details>
      <h3>Suas solicitações</h3>{!requests.length && <div className="portal-empty"><strong>Seu atendimento fica registrado aqui</strong><p>Abra “Nova solicitação” para enviar sua dúvida e acompanhar o status e a resposta da equipe nesta área.</p></div>}{requests.map(item => <article key={item.id} id={`solicitacao-${item.id}`} className="portal-task account-request"><div className="account-section-heading"><h4>{item.subject}</h4>{item.unread && <span className="account-pill account-pill-new">Nova resposta</span>}</div><p>{statuses[item.status]} · Atualizada em {date(item.updated_at)}</p><p className="portal-text">{item.message}</p>{item.reply && <><blockquote className="portal-text"><strong>Resposta da Plataforma de Privacidade</strong><p>{item.reply}</p></blockquote>{item.unread ? <PortalForm action="leitura" label={`Marcar resposta como lida: ${item.subject}`} submitLabel="Marcar como lida"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="version" value={item.replyVersion} /></PortalForm> : <p className="account-read-status">✓ Resposta lida</p>}</>}</article>)}
    </section>}
  </div>;
}
