export const privacyServices = [
  { id: "diagnostico", title: "Diagnóstico e plano de adequação à LGPD", description: "Entenda como os dados pessoais circulam na organização, identifique lacunas e organize uma evolução compatível com o seu contexto.", items: ["Entrevistas com as áreas e levantamento dos processos que utilizam dados pessoais.", "Análise de práticas, documentos e controles já existentes.", "Identificação de riscos e priorização por impacto e esforço.", "Plano de ação com responsáveis, entregáveis e acompanhamento das pendências."] },
  { id: "mapeamento", title: "Data mapping e registro das operações", description: "Transforme o uso de dados em um inventário claro, que possa apoiar decisões e ser mantido pela equipe.", items: ["Mapeamento de origens, finalidades, categorias de dados e titulares.", "Identificação de sistemas, áreas, terceiros e compartilhamentos envolvidos.", "Organização do ROPA, o registro das operações de tratamento.", "Levantamento de retenção, descarte e controles, conforme o escopo definido."] },
  { id: "avaliacoes", title: "Avaliações de privacidade e legítimo interesse", description: "Documente a análise de atividades que exigem maior atenção e conecte os resultados às decisões de negócio.", items: ["Levantamento do contexto, das finalidades e das partes envolvidas.", "Apoio à elaboração de LIA, a avaliação de legítimo interesse, quando aplicável.", "Análise de necessidade, impactos e salvaguardas do tratamento avaliado.", "Recomendações de mitigação e registro dos pontos de decisão."] },
  { id: "politicas", title: "Políticas, procedimentos e governança", description: "Conecte a documentação às rotinas de quem coleta, usa, compartilha e protege informações.", items: ["Revisão e elaboração de políticas e avisos de privacidade.", "Procedimentos para atendimento de solicitações de titulares.", "Diretrizes para retenção, descarte e compartilhamento de dados.", "Definição de papéis, rotinas de revisão e registros de evidências."] },
];

export const trainingCatalog = [
  { id: "palestras", title: "Palestras de conscientização", format: "Sensibilização", audience: "Equipes em geral, lideranças e públicos definidos pela organização.", description: "Conversas objetivas que aproximam segurança e privacidade das escolhas do dia a dia.", topics: ["Cuidados com dados pessoais e informações confidenciais.", "Reconhecimento de situações de risco e comunicação interna.", "Boas práticas no trabalho digital e no compartilhamento de informações.", "Responsabilidades das pessoas dentro da cultura de proteção."], deliverable: "Roteiro e abordagem ajustados ao público, com espaço para dúvidas e discussão de exemplos." },
  { id: "minicursos", title: "Minicursos aplicados", format: "Aprofundamento", audience: "Profissionais que precisam compreender um tema e aplicá-lo em sua rotina.", description: "Percursos de aprendizagem focados, com linguagem acessível e atividades orientadas ao contexto do negócio.", topics: ["Fundamentos de proteção de dados e governança de privacidade.", "Organização de inventários, registros e evidências.", "Introdução à gestão de riscos e aos controles de segurança.", "Discussão de situações práticas e decisões recorrentes."], deliverable: "Programa, materiais e atividades definidos em conjunto com a organização." },
  { id: "sob-medida", title: "Treinamentos sob medida", format: "Programa personalizado", audience: "Áreas como RH, marketing, atendimento, jurídico, tecnologia, compras e gestão.", description: "Capacitação construída a partir dos processos, dos riscos e dos desafios reais de cada equipe.", topics: ["Levantamento de necessidades e objetivos de aprendizagem.", "Exemplos adaptados às atividades e aos fluxos da área.", "Orientação sobre políticas e procedimentos internos selecionados.", "Atividades e avaliação de aprendizagem quando previstas no escopo."], deliverable: "Plano de capacitação com público, conteúdos, formato e critérios de acompanhamento acordados." },
  { id: "tabletop-incidentes", title: "Tabletop de resposta a incidentes", format: "Simulação de decisões", audience: "Lideranças, tecnologia, segurança, privacidade, jurídico e comunicação.", description: "Exercício guiado de discussão para praticar decisões diante de um cenário simulado de incidente de segurança da informação.", topics: ["Construção de cenário compatível com o ambiente da organização.", "Definição de participantes, papéis e regras do exercício.", "Discussão de escalonamento, investigação, comunicação e recuperação.", "Debriefing com lacunas identificadas e oportunidades de melhoria."], deliverable: "Registro das observações e plano de melhorias. O exercício de discussão não realiza ataques em sistemas." },
  { id: "tabletop-continuidade", title: "Tabletop de continuidade de negócios", format: "Preparação e resiliência", audience: "Gestão, operações, tecnologia e responsáveis por processos essenciais.", description: "Exercício para discutir como manter e retomar atividades essenciais diante de uma interrupção simulada.", topics: ["Seleção de processos, dependências e cenário de interrupção.", "Discussão das prioridades de operação e dos critérios de recuperação.", "Coordenação entre áreas, fornecedores e responsáveis por decisões.", "Identificação de pontos de melhoria nos planos e na comunicação."], deliverable: "Relatório do exercício com ações priorizadas para aprimorar a preparação da organização." },
];

export const auditServices = [
  { id: "iso-27001", title: "ISO 27001 — implementação e auditoria interna", description: "Implementação e avaliação do sistema de gestão de segurança da informação com base no escopo e nos critérios acordados.", items: ["Diagnóstico de lacunas e planejamento da implementação.", "Apoio à estruturação de políticas, processos e controles de segurança da informação.", "Planejamento e definição do programa de auditoria.", "Entrevistas, análise documental e amostragem de evidências.", "Avaliação da relação entre riscos, controles e práticas de gestão.", "Relatório de constatações e recomendações para tratamento."] },
  { id: "iso-27701", title: "ISO 27701 — implementação e auditoria interna", description: "Implementação e avaliação do sistema de gestão da privacidade, considerando os processos e as atividades da organização.", items: ["Diagnóstico de lacunas e planejamento da implementação.", "Apoio à estruturação de políticas, processos e controles de privacidade.", "Delimitação dos processos, responsabilidades e informações a avaliar.", "Verificação de documentação, registros e controles de privacidade.", "Entrevistas com as áreas envolvidas no tratamento de dados pessoais.", "Registro de lacunas e oportunidades de melhoria."] },
  { id: "iso-42001", title: "ISO 42001 — implementação e auditoria interna", description: "Implementação e avaliação do sistema de gestão de inteligência artificial, considerando a governança e os riscos dos usos de IA.", items: ["Diagnóstico de lacunas e planejamento da implementação.", "Apoio à estruturação de políticas, processos e controles para a gestão de IA.", "Definição do escopo dos usos e processos de IA avaliados.", "Análise de governança, responsabilidades e documentação.", "Avaliação das práticas de gestão de riscos e acompanhamento.", "Relatório com constatações e ações recomendadas."] },
  { id: "itgc", title: "ITGC e cibersegurança", description: "Avaliação de controles gerais de tecnologia e de práticas de segurança que sustentam os processos do negócio.", items: ["Gestão de acessos e revisões de permissões.", "Gestão de mudanças e operações de tecnologia.", "Evidências relacionadas a backup, recuperação e monitoramento.", "Testes de controles e análise de desenho e execução, conforme o escopo."] },
  { id: "cis-nist", title: "Gap analysis — CIS Controls e NIST CSF", description: "Levantamento de lacunas para orientar uma evolução de segurança baseada no contexto e nas prioridades da organização.", items: ["Escolha do referencial e definição do conjunto de práticas avaliado.", "Levantamento do estado atual e das evidências disponíveis.", "Identificação das diferenças em relação ao objetivo acordado.", "Roteiro de melhorias com prioridades, dependências e responsáveis."] },
  { id: "pci-dss", title: "PCI DSS — implementação e preparação", description: "Apoio à organização dos controles e das evidências necessários à preparação para uma avaliação PCI DSS.", items: ["Entendimento do ambiente e dos fluxos de dados de pagamento.", "Diagnóstico das lacunas dentro do escopo definido.", "Apoio ao planejamento e à implementação das melhorias.", "Organização de evidências e preparação das equipes para a avaliação."] },
];

export const companyValues = [
  { title: "Clareza para decidir", description: "Traduzir assuntos técnicos em informações compreensíveis, com prioridades, responsabilidades e próximos passos." },
  { title: "Respeito às pessoas", description: "Considerar as pessoas por trás dos dados e os impactos das decisões sobre clientes, equipes e parceiros." },
  { title: "Pragmatismo na execução", description: "Conectar recomendações à operação, aos recursos disponíveis e ao contexto de cada organização." },
  { title: "Responsabilidade com a informação", description: "Tratar confidencialidade, integridade, disponibilidade e privacidade como parte da forma de trabalhar." },
  { title: "Colaboração entre áreas", description: "Aproximar negócio, tecnologia, segurança e privacidade para construir soluções que possam ser sustentadas." },
  { title: "Evolução contínua", description: "Revisar práticas, aprender com os resultados e transformar planos de ação em melhorias acompanháveis." },
];

export const privacyFaqs = [
  { question: "Por onde começar a adequação à LGPD?", answer: "O ponto de partida é compreender as atividades que utilizam dados pessoais e o que já existe de governança. O diagnóstico organiza esse cenário e orienta um plano de ação. A profundidade, os documentos e as etapas do trabalho são definidos de acordo com o contexto da organização." },
  { question: "O que é DPO as a Service?", answer: "É a prestação terceirizada da função de encarregado pelo tratamento de dados pessoais, com atuação e responsabilidades acordadas. O serviço pode apoiar a interlocução com titulares, a orientação das equipes e a rotina de governança. As decisões e responsabilidades próprias da organização permanecem com seus responsáveis." },
  { question: "Qual é a diferença entre data mapping, ROPA e LIA?", answer: "Data mapping é o levantamento dos fluxos de dados. ROPA organiza o registro das operações de tratamento. LIA é uma avaliação de legítimo interesse aplicada aos tratamentos para os quais essa análise é pertinente. Os instrumentos têm finalidades diferentes e podem se complementar no programa de privacidade." },
  { question: "A consultoria também ajuda a implementar as melhorias?", answer: "O trabalho pode abranger diagnóstico, planejamento, elaboração de documentos, orientação às áreas e acompanhamento da implementação. Entregas, responsabilidades, cadência de reuniões e critérios de conclusão são definidos na proposta." },
  { question: "Já temos políticas. Precisamos começar do zero?", answer: "Não necessariamente. Documentos e processos existentes podem ser avaliados para identificar o que deve ser aproveitado, atualizado ou complementado. O objetivo é conectar a documentação à realidade da operação e à capacidade de manutenção da equipe." },
];

export const trainingFaqs = [
  { question: "Como escolher o formato de capacitação?", answer: "A escolha considera o público, a experiência prévia, o objetivo e o tempo disponível. Palestras favorecem sensibilização; minicursos permitem aprofundamento; treinamentos sob medida conectam os conteúdos às rotinas da equipe; tabletop exercita decisões em um cenário simulado." },
  { question: "Os conteúdos podem ser adaptados ao nosso setor?", answer: "A proposta pode ser construída a partir dos processos, das políticas e dos desafios da organização. Público, temas, materiais, formato, carga horária e logística são definidos antes da execução." },
  { question: "Tabletop é um teste técnico de invasão?", answer: "Não. Tabletop é um exercício guiado de discussão, no qual os participantes tomam decisões diante de um cenário fictício. Ele ajuda a observar coordenação, comunicação e conhecimento dos procedimentos. Testes técnicos em sistemas exigem um escopo específico." },
  { question: "Existem turmas abertas, datas ou certificados?", answer: "Esta página apresenta os formatos que podem compor uma proposta. Disponibilidade, datas, duração, modalidade, materiais e eventual emissão de certificados precisam ser definidos na contratação. O formulário solicita uma proposta; não realiza inscrição em uma turma." },
  { question: "O que a organização recebe depois de um tabletop?", answer: "O escopo pode incluir um registro das observações, lacunas identificadas e recomendações priorizadas. As entregas e o nível de detalhe são acordados na proposta, de acordo com o objetivo e os participantes do exercício." },
];

export const auditFaqs = [
  { question: "O serviço inclui implementação das normas ISO?", answer: "Sim. Além das auditorias internas, a Plataforma de Privacidade realiza o trabalho de implementação das ISO 27001, ISO 27701 e ISO 42001. O escopo pode incluir diagnóstico de lacunas, planejamento, estruturação de políticas, processos e controles e acompanhamento da implementação. Etapas, entregas e responsabilidades são definidas na proposta." },
  { question: "Auditoria interna emite certificação ISO?", answer: "A auditoria interna avalia práticas e evidências para apoiar o sistema de gestão e sua melhoria. Ela não equivale à auditoria de certificação e não emite certificado ISO. Uma eventual certificação envolve um processo próprio com um organismo certificador." },
  { question: "Como diferenciar auditoria e gap analysis?", answer: "Uma auditoria utiliza critérios e um programa definidos para avaliar evidências e registrar constatações. Uma análise de lacunas identifica diferenças entre a situação atual e um referencial ou objetivo acordado, ajudando a organizar prioridades de evolução. A escolha depende do que a organização precisa decidir." },
  { question: "O serviço de PCI DSS inclui certificação?", answer: "O serviço apresentado é de apoio à implementação e preparação para avaliação. Não representa emissão de certificação, atestado ou garantia de conformidade. O processo de validação aplicável e os participantes necessários devem ser definidos de acordo com o contexto da organização." },
  { question: "A avaliação inclui teste de invasão ou varredura de vulnerabilidades?", answer: "Essas atividades não estão automaticamente incluídas. Métodos, ambientes, acessos, limites e autorizações de eventuais testes técnicos precisam constar em um escopo específico. A proposta estabelece o que será examinado e como as evidências serão coletadas." },
  { question: "Como são apresentados os resultados?", answer: "A proposta pode prever uma visão executiva e um relatório detalhado com escopo, critérios, evidências, constatações e recomendações. As ações podem ser organizadas por prioridade, responsável e prazo acordado, facilitando o acompanhamento pelas equipes." },
  { question: "É possível acompanhar a correção das lacunas?", answer: "Sim, esse acompanhamento pode compor o escopo. Ele pode incluir reuniões de evolução, revisão das evidências de implementação e atualização do plano de ação. Reavaliações e novas amostragens são definidas conforme os objetivos do trabalho." },
];
