import Link from "next/link";
import { PageHero, SectionHeading, ServiceCard, FAQ, CtaBand, Steps } from "@/components/Editorial";
import { auditServices, auditFaqs } from "@/lib/content";

export const metadata = { title: "Auditorias e Avaliações", description: "Implementação e auditorias internas ISO 27001, ISO 27701 e ISO 42001, ITGC, cibersegurança, gap analysis CIS e NIST CSF e preparação para PCI DSS." };

export default function AuditsPage() {
  return <main id="conteudo"><PageHero eyebrow="Auditorias e Avaliações" title="Evidências para decidir. Clareza para evoluir." description="Conheça o estado dos seus controles, identifique lacunas e transforme avaliações de segurança, privacidade e governança em prioridades de ação."><p className="page-kicker">Visão executiva e profundidade técnica</p><ul className="feature-list"><li>Implementação e auditorias internas de sistemas de gestão</li><li>ITGC e cibersegurança</li><li>Avaliações de lacunas e preparação</li></ul><Link className="button button--navy" href="/contato?interesse=auditoria">Definir o escopo da avaliação ↗</Link></PageHero>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Frentes de atuação" title="Escolha o serviço que responde à sua necessidade." description="Referencial, abrangência, critérios, profundidade e entregas são acordados antes do início do trabalho. A seleção considera o objetivo da implementação ou da avaliação e o contexto do negócio." /><div className="card-grid card-grid--two">{auditServices.map((service, index) => <ServiceCard key={service.id} number={String(index + 1).padStart(2, "0")} title={service.title} description={service.description}><ul className="feature-list">{service.items.map(item => <li key={item}>{item}</li>)}</ul></ServiceCard>)}</div><div className="notice"><strong>Escopo transparente.</strong> Na ISO 27001, ISO 27701, ISO 42001 e PCI DSS, você escolhe o que a Plataforma de Privacidade faz pela sua organização: implementação, auditoria interna ou preparação para avaliação. Por independência, quem implementa não audita o mesmo escopo, e essa definição fica clara em contrato. Nenhum desses serviços emite certificação.</div></div></section>
    <section className="section section--tint"><div className="shell"><SectionHeading eyebrow="Quando avaliar" title="Uma avaliação deve ajudar a tomar uma decisão." /><div className="card-grid"><ServiceCard title="Entender a situação atual" description="Mapear práticas e identificar o que precisa de atenção antes de iniciar um ciclo de investimento." /><ServiceCard title="Preparar uma avaliação externa" description="Organizar documentos, equipes e evidências, identificando lacunas que exigem tratamento prévio." /><ServiceCard title="Revisar controles em operação" description="Avaliar como os procedimentos definidos estão sendo executados e onde existem oportunidades de melhoria." /></div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Como trabalhamos" title="Do planejamento à leitura dos resultados." /><Steps items={[{title:"Escopo e critérios",description:"Acordar objetivos, referencial, processos, ambientes, limites e período da avaliação."},{title:"Evidências e entrevistas",description:"Examinar os materiais disponíveis, ouvir responsáveis e executar procedimentos previstos."},{title:"Análise e constatações",description:"Consolidar evidências, discutir o contexto e registrar lacunas, riscos e oportunidades."},{title:"Plano e acompanhamento",description:"Apresentar resultados e organizar ações. Acompanhamento posterior definido no escopo."}]} /></div></section>
    <section className="section section--navy"><div className="shell split-layout"><div><p className="page-kicker">Entregáveis</p><h2>Resultados que orientam próximos passos.</h2><p>O relatório permite entender a constatação, sua relação com os critérios e o que a organização pode fazer a seguir. Formato e detalhamento são definidos no escopo.</p></div><ul className="feature-list"><li>Escopo, critérios e procedimentos executados.</li><li>Visão executiva dos principais resultados.</li><li>Constatações sustentadas pelas evidências avaliadas.</li><li>Identificação de lacunas e recomendações de melhoria.</li><li>Plano de ação com prioridades e responsáveis acordados.</li><li>Reunião de apresentação e esclarecimento dos resultados.</li></ul></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Preparação" title="O que ajuda a iniciar o trabalho?" description="Não é necessário ter todos os documentos prontos para a primeira conversa." /><div className="card-grid card-grid--two"><ServiceCard title="Contexto da organização"><ul className="feature-list"><li>Objetivo e necessidades das partes interessadas.</li><li>Processos, unidades e ambientes envolvidos.</li><li>Referenciais de interesse e avaliações anteriores.</li><li>Prazo desejado e responsáveis pelo acompanhamento.</li></ul></ServiceCard><ServiceCard title="Materiais e evidências"><ul className="feature-list"><li>Políticas, procedimentos e registros relacionados ao escopo.</li><li>Inventários, mapas de processos e visão dos sistemas.</li><li>Registros de controles e planos de ação existentes.</li><li>Disponibilidade para entrevistas e esclarecimentos.</li></ul></ServiceCard></div></div></section>
    <section className="section section--tint"><div className="shell narrow"><SectionHeading eyebrow="Dúvidas frequentes" title="Escopo claro desde o primeiro contato." /><FAQ items={auditFaqs} /></div></section><CtaBand title="Qual pergunta sua próxima avaliação precisa responder?" description="Compartilhe seu objetivo e o referencial de interesse para organizarmos uma proposta." href="/contato?interesse=auditoria" label="Conversar sobre uma avaliação ↗" />
  </main>;
}
