import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import Link from "next/link";
import { SESSION_COOKIE, sessionUser, adminAccessAllowed } from "@/lib/server/auth";
import { adminData } from "@/lib/server/portal";
import PortalForm from "@/components/PortalForm";
import AdminAccountDeletion, { DeleteAccountButton } from "@/components/AdminAccountDeletion";
import AdminAccountEditor from "@/components/AdminAccountEditor";
import AdminOverview, { adminDate, requestLabels } from "@/components/AdminOverview";
import AdminOperations from "@/components/AdminOperations";

export const runtime = "nodejs";
export const metadata = { title: "Administração", robots: { index: false, follow: false } };
const tabs = [["visao-geral", "Visão geral", "◈"], ["usuarios", "Usuários", "◎"], ["solicitacoes", "Solicitações", "▤"], ["emails", "Emails", "✉"], ["servicos", "Serviços", "◇"], ["operacao", "Operação e segurança", "⊙"]];
const roles = { usuario: "Usuário cadastrado", cliente: "Cliente Plataforma de Privacidade", admin: "Administrador" };
const emailStatuses = { sending: "Envio iniciado", accepted: "Aceito pelo SMTP", failed: "Falha no envio", local: "Somente local" };
const categories = { cadastro: "Código de cadastro", recuperacao: "Recuperação de senha", contato: "Formulário de contato", newsletter: "Newsletter", verificacao: "Confirmação de email", teste: "Teste SMTP", outro: "Outro" };

function Filters({ tab, filters }) {
  return <form method="get" action="/administracao" className="admin-filters" aria-label="Filtrar registros">
    <input type="hidden" name="tab" value={tab} />
    {filters.userId && <input type="hidden" name="userId" value={filters.userId} />}
    <label className="form-field admin-search">Pesquisar<input type="search" name="q" defaultValue={filters.q} maxLength={160} placeholder={tab === "emails" ? "Destinatário ou assunto" : tab === "usuarios" ? "Nome ou email" : "Assunto, nome ou email"} /></label>
    {tab === "usuarios" && <><label className="form-field">Perfil<select name="role" defaultValue={filters.role}><option value="">Todos os perfis</option>{Object.entries(roles).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="form-field">Solicitações<select name="status" defaultValue={filters.status === "ativas" ? "ativas" : ""}><option value="">Todos os usuários</option><option value="ativas">Com solicitações em aberto</option></select></label></>}
    {tab === "solicitacoes" && <label className="form-field">Status<select name="status" defaultValue={Object.hasOwn(requestLabels, filters.status) || filters.status === "ativas" ? filters.status : ""}><option value="">Todos os status</option><option value="ativas">Abertas e em andamento</option>{Object.entries(requestLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>}
    {tab === "emails" && <><label className="form-field">Status<select name="status" defaultValue={Object.hasOwn(emailStatuses, filters.status) ? filters.status : ""}><option value="">Todos os status</option>{Object.entries(emailStatuses).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="form-field">Tipo de envio<select name="category" defaultValue={filters.category}><option value="">Todos os tipos</option>{Object.entries(categories).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="form-field">Período<select name="period" defaultValue={filters.period}><option value="">Todo o histórico</option><option value="1">Últimas 24 horas</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option></select></label></>}
    <button className="admin-button">Filtrar</button><Link className="admin-clear" href={`/administracao?tab=${tab}`}>Limpar</Link>
  </form>;
}

function Pagination({ tab, filters, pagination }) {
  const href = page => { const query = new URLSearchParams({ tab, ...filters, page: String(page) }); for (const [key, value] of [...query]) if (!value) query.delete(key); return `/administracao?${query}`; };
  return <nav className="admin-pagination" aria-label="Paginação"><span>{pagination.total} {pagination.total === 1 ? "registro" : "registros"} · Página {pagination.page} de {pagination.pages}</span><div>{pagination.page > 1 && <Link href={href(pagination.page - 1)}>← Anterior</Link>}{pagination.page < pagination.pages && <Link href={href(pagination.page + 1)}>Próxima →</Link>}</div></nav>;
}

function ServiceFields({ clients, service }) {
  return <>{service && <input type="hidden" name="id" value={service.id} />}<label className="form-field">Cliente<select name="userId" required defaultValue={service?.user_id || ""}><option value="" disabled>Selecione um cliente</option>{clients.map(user => <option key={user.id} value={user.id}>{user.name} — {user.email}</option>)}</select></label><label className="form-field">Serviço<input name="title" defaultValue={service?.title || ""} required maxLength={160} /></label><label className="form-field">Descrição<textarea name="description" defaultValue={service?.description || ""} required maxLength={3000} rows={3} /></label><div className="portal-fields"><label className="form-field">Status<select name="status" defaultValue={service?.status || "planejado"}><option value="planejado">Planejado</option><option value="andamento">Em andamento</option><option value="concluido">Concluído</option></select></label><label className="form-field">Prazo<input name="dueDate" type="date" defaultValue={service?.due_date || ""} /></label></div></>;
}

export default async function AdministrationPage({ searchParams }) {
  const user = sessionUser((await cookies()).get(SESSION_COOKIE)?.value);
  if (!user) redirect("/login");
  if (user.role !== "admin") redirect("/minha-conta");
  if (process.env.NODE_ENV === "production" && !user.emailVerified) redirect("/minha-conta/configuracoes?seguranca=email");
  if (!adminAccessAllowed(user)) redirect("/minha-conta/configuracoes?seguranca=2fa");
  const data = adminData(user, await searchParams), { tab, filters } = data;
  const title = tabs.find(item => item[0] === tab)[1];
  return <main id="conteudo" className="admin-page"><div className="shell admin-shell">
    <aside className="admin-sidebar"><div className="admin-brand"><span className="admin-symbol" aria-hidden="true">P</span><div><strong>Plataforma de Privacidade</strong><small>Administração</small></div></div><nav aria-label="Administração">{tabs.map(([value, label, icon]) => <Link key={value} href={`/administracao?tab=${value}`} aria-current={tab === value ? "page" : undefined}><span aria-hidden="true">{icon}</span>{label}{value === "solicitacoes" && data.summary.openRequests > 0 && <b>{data.summary.openRequests}</b>}</Link>)}</nav><div className="admin-sidebar-footer"><span className="admin-tag">ADMINISTRADOR</span><strong>{user.name}</strong><Link href="/minha-conta/configuracoes">Minha conta e segurança →</Link></div></aside>
    <div className="admin-content"><header className="admin-header"><div><p className="admin-kicker">CENTRAL DE ADMINISTRAÇÃO</p><h1>{title}</h1><p>{tab === "visao-geral" ? `Olá, ${user.name}. Aqui está o panorama da operação.` : "Gerencie a operação e acompanhe os registros do site."}</p></div><Link className="admin-profile-link" href="/minha-conta">{user.name}<span>Administrador ↗</span></Link></header>
      {tab === "visao-geral" && <AdminOverview summary={data.summary} />}
      {tab === "operacao" && <AdminOperations user={user} />}
      {tab === "usuarios" && <section className="admin-card"><div className="admin-section-heading"><div><h2>Usuários e clientes</h2><p>Confira perfis, datas de cadastro e atendimentos pendentes.</p></div><span className="admin-count">{data.pagination.usuarios.total} contas</span></div><Filters tab={tab} filters={filters} />
        <AdminAccountDeletion><div className="admin-user-list">{data.users.map(item => <article key={item.id} className="admin-user"><div className="admin-user-top"><span className="admin-avatar" aria-hidden="true">{item.name.slice(0, 1).toLocaleUpperCase("pt-BR")}</span><div className="admin-user-identity"><h3>{item.name}</h3><p>{item.email}</p></div><span className={`admin-badge ${item.role}`}>{roles[item.role]}</span></div><div className="admin-user-meta"><span>Cadastro: {adminDate(item.created_at)}</span><span>{item.verified_at ? "Email confirmado" : "Sem confirmação registrada"}</span><Link href={`/administracao?tab=solicitacoes&userId=${item.id}&status=ativas`}>{item.open_requests} solicitações em aberto →</Link></div><details className="admin-user-details"><summary>Conferir perfil e acesso</summary><p>Email: {item.email}<br />Confirmado em: {adminDate(item.verified_at)}</p>{item.role === "admin" ? <p>Esta conta possui acesso à central de administração.</p> : <PortalForm action="acesso" label={`Salvar acesso de ${item.name}`}><input name="userId" type="hidden" value={item.id} /><label className="form-field">Perfil<select name="role" defaultValue={item.role}><option value="usuario">Usuário cadastrado</option><option value="cliente">Cliente Plataforma de Privacidade</option></select></label><p className="admin-muted">Libere o perfil de cliente após confirmar a contratação.</p></PortalForm>}</details><DeleteAccountButton account={{ id: item.id, name: item.name, email: item.email, role: item.role }} ownAccount={item.id === user.id}><AdminAccountEditor account={{ id: item.id, name: item.name, email: item.email, role: item.role, version: item.version }} ownAccount={item.id === user.id} /></DeleteAccountButton></article>)}</div></AdminAccountDeletion>
        {!data.users.length && <div className="admin-empty"><strong>Nenhum usuário encontrado</strong><p>Ajuste a pesquisa ou limpe os filtros.</p></div>}<Pagination tab={tab} filters={filters} pagination={data.pagination.usuarios} /></section>}
      {tab === "solicitacoes" && <section className="admin-card"><h2>Solicitações de clientes</h2><p>Leia a mensagem, responda e acompanhe o andamento do atendimento.</p><Filters tab={tab} filters={filters} />{filters.userId && <p className="admin-filter-note">Exibindo solicitações do usuário selecionado. <Link href="/administracao?tab=solicitacoes">Ver todos os usuários</Link></p>}
        {!data.requests.length && <div className="admin-empty"><strong>Nenhuma solicitação encontrada</strong><p>Não há solicitações para os filtros escolhidos.</p></div>}{data.requests.map(item => <article key={item.id} className="admin-request"><div className="admin-section-heading"><h3>{item.subject}</h3><span className={`admin-badge ${item.status}`}>{requestLabels[item.status]}</span></div><p className="admin-muted">{item.name} · {item.email}</p><p className="admin-muted">Criada em {adminDate(item.created_at)} · Atualizada em {adminDate(item.updated_at)}</p><p className="portal-text">{item.message}</p><PortalForm action="resposta" label={`Responder: ${item.subject}`}><input name="id" type="hidden" value={item.id} /><label className="form-field">Resposta<textarea name="reply" defaultValue={item.reply} required maxLength={5000} rows={4} /></label><label className="form-field">Status<select name="status" defaultValue={item.status}>{Object.entries(requestLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></PortalForm></article>)}<Pagination tab={tab} filters={filters} pagination={data.pagination.solicitacoes} /></section>}
      {tab === "emails" && <section className="admin-card"><h2>Histórico de envio de emails</h2><p>O aceite SMTP confirma o recebimento pelo servidor de email. A entrega na caixa de entrada não é confirmada por este registro.</p><p className="admin-muted">Horários de Brasília. O histórico registra os envios a partir da ativação deste painel.</p><Filters tab={tab} filters={filters} />
        {!data.emails.length ? <div className="admin-empty"><strong>Nenhum envio encontrado</strong><p>Os próximos envios de cadastro, contato, recuperação de senha e newsletter aparecerão aqui. Se há filtros ativos, tente limpá-los.</p></div> : <div className="admin-table-wrap"><table className="admin-table"><caption className="sr-only">Registros de email e diagnóstico SMTP</caption><thead><tr><th scope="col">Horário / tipo</th><th scope="col">Destinatário / assunto</th><th scope="col">Status / diagnóstico</th></tr></thead><tbody>{data.emails.map(item => <tr key={item.id}><td><time dateTime={new Date(item.created_at).toISOString()}>{adminDate(item.created_at)}</time><small>{categories[item.category] || "Outro"}</small></td><td><strong>{item.recipient}</strong><small>{item.subject}</small></td><td><span className={`admin-badge ${item.status}`}>{emailStatuses[item.status] || "Desconhecido"}</span>{item.error_message && <p className="admin-error-detail">{item.error_message}</p>}<small>{item.smtp_code ? `SMTP ${item.smtp_code}` : item.status === "accepted" ? "Destinatário aceito" : item.status === "local" ? "Sem envio externo" : item.status === "sending" ? "Aguardando conclusão do envio" : "Sem resposta SMTP registrada"}{item.error_code && ` · ${item.error_code}`}</small><details className="admin-email-details"><summary>Detalhes do envio</summary><p>Registro: {item.id}<br />Concluído em: {adminDate(item.completed_at)}{item.message_id && <><br />ID da mensagem: {item.message_id}</>}</p></details></td></tr>)}</tbody></table></div>}<Pagination tab={tab} filters={filters} pagination={data.pagination.emails} /></section>}
      {tab === "servicos" && <section className="admin-card"><h2>Acompanhamento de serviços</h2><p>Mantenha contratos, prazos e entregas atualizados para seus clientes.</p>{data.clients.length ? <details className="admin-service-new"><summary>Cadastrar serviço contratado</summary><PortalForm action="servico" label="Cadastrar serviço" reset><ServiceFields clients={data.clients} /></PortalForm></details> : <p className="admin-filter-note">Libere o perfil de cliente em Usuários para cadastrar serviços.</p>}{!data.services.length && <div className="admin-empty"><strong>Nenhum serviço cadastrado</strong><p>Os serviços contratados aparecerão nesta área.</p></div>}{data.services.map(item => <details key={item.id} className="portal-plan"><summary>{item.title} · {item.name}</summary><PortalForm action="servico" label={`Atualizar serviço: ${item.title}`}><ServiceFields clients={data.clients} service={item} /></PortalForm></details>)}<Pagination tab={tab} filters={filters} pagination={data.pagination.servicos} /></section>}
    </div>
  </div></main>;
}
