import Link from "next/link";
import LegalIdentity from "@/components/LegalIdentity";
import { PageHero } from "@/components/Editorial";
export const metadata = {title:"Termos de Uso",description:"Condições de utilização das informações, formulários e ferramentas do site Plataforma de Privacidade."};
export default function TermsPage() {
  return <main id="conteudo"><PageHero eyebrow="Transparência / Termos de Uso" title="Um uso responsável começa por informações claras." description="Entenda a finalidade deste site e os limites dos recursos disponíveis." /><section className="section"><div className="shell narrow legal-content">
    <LegalIdentity />
    <section><h2>1. Finalidade do site</h2><p>O site apresenta serviços de consultoria em privacidade, avaliação de terceiros, educação, auditorias e avaliações. Também permite registrar solicitações de contato, assinar uma newsletter e gerar uma autoavaliação de segurança e privacidade.</p><p>As descrições apresentam possibilidades de escopo. Entregas, preços, cronogramas, disponibilidade e responsabilidades são definidos em proposta ou contrato específico.</p></section>
    <section><h2>2. Contato e propostas</h2><p>Enviar o formulário registra uma solicitação e gera um protocolo. Esse registro não confirma reunião, reserva de horário, inscrição em treinamento ou contratação. O agendamento e as condições do serviço dependem de alinhamento posterior.</p><p>As informações fornecidas devem ser corretas e pertinentes à solicitação. Não inclua senhas, documentos pessoais ou conteúdo confidencial desnecessário no primeiro contato.</p></section>
    <section><h2>3. Uso da autoavaliação</h2><p>Os indicadores Security Score e Privacy Score desta ferramenta são calculados sobre respostas declaradas pelo usuário, de acordo com a metodologia apresentada. Eles servem como orientação inicial e não substituem análise especializada, diligência sobre fornecedores, auditoria, parecer jurídico ou verificação de evidências.</p><p>O resultado não constitui certificação ISO, validação PCI DSS, comprovação integral de adequação à LGPD ou garantia de segurança. O suporte comercial relacionado a PCI DSS abrange implementação e preparação para avaliação, sem promessa de certificação.</p><p>As recomendações devem ser avaliadas no contexto da organização antes da implementação. Os documentos anexados não são analisados automaticamente e não alteram a pontuação.</p></section>
    <section><h2>4. Responsabilidade pelas informações e pelos anexos</h2><p>Responda pela empresa somente quando tiver conhecimento e autorização para fornecer as informações. Envie arquivos relevantes, livres de credenciais e de dados pessoais desnecessários.</p><p>Avaliações vinculadas a contas exigem acesso do titular. Nas avaliações sem conta, o link privado permite acessar o relatório e gerenciar as evidências. Sua guarda e seu compartilhamento precisam respeitar as autorizações da organização. A exclusão de um anexo remove sua disponibilidade na avaliação e deve ser confirmada pelo usuário.</p></section>
    <section><h2>5. Newsletter e ambientes externos</h2><p>A assinatura exige autorização e confirmação por e-mail. O cancelamento pode ser solicitado pelo link enviado ou pelo formulário de contato. A existência de uma inscrição não assegura uma periodicidade específica de publicação.</p><p>Conteúdos ou canais externos têm regras próprias. As referências a leis, normas e frameworks indicam assuntos de trabalho e não representam endosso, vínculo institucional ou certificação da Plataforma de Privacidade por seus respectivos responsáveis.</p></section>
    <section><h2>6. Contas e acesso administrativo</h2><p>O cadastro exige confirmação do email e aceite dos termos. Guarde sua senha e não compartilhe códigos de confirmação, chaves do autenticador ou códigos de recuperação. Administradores precisam ativar a autenticação em duas etapas antes de acessar a administração em produção. Alterações de email ou perfil podem encerrar as sessões e exigir nova confirmação.</p><p>Recursos de documentos, serviços e atendimento dependem do perfil de acesso liberado. Administradores autorizados podem editar e excluir contas. A exclusão remove os dados vinculados à área da conta; contatos, inscrições na newsletter, registros operacionais e backups seguem os critérios descritos na política de privacidade.</p></section>
    <section><h2>7. Disponibilidade e uso adequado</h2><p>Os recursos dependem da disponibilidade do servidor e dos serviços configurados. O site pode passar por manutenção e atualizações. Não utilize os formulários para conteúdo ilícito, envio automatizado abusivo ou acesso a avaliações sem autorização.</p><p>Para informar um problema ou tratar de dados pessoais, utilize o <Link href="/contato">formulário de contato</Link>. As condições de tratamento de dados estão descritas na <Link href="/politica-de-privacidade">Política de Privacidade</Link>.</p></section>
  </div></section></main>;
}
