import Link from "next/link";
import { PageHero, SectionHeading, ServiceCard, FAQ, CtaBand, Steps } from "@/components/Editorial";
import { privacyServices, privacyFaqs } from "@/lib/content";

export const metadata = { title: "Consultoria em Privacidade e LGPD", description: "DPO as a Service, diagnóstico, adequação à LGPD, data mapping, ROPA, LIA e políticas conectadas à rotina da sua organização." };

export default function PrivacyConsultingPage() {
  return <main id="conteudo">
    <PageHero eyebrow="Consultoria em Privacidade" title="Proteção de dados que faz parte da operação." description="Da primeira avaliação à rotina do encarregado: organize processos, documente decisões e conecte a privacidade às necessidades do seu negócio."><p className="page-kicker">Do diagnóstico à continuidade</p><ul className="feature-list"><li>DPO as a Service</li><li>Adequação à LGPD</li><li>Mapeamento, registros e avaliações</li><li>Políticas e governança</li></ul><Link className="button button--navy" href="/contato?interesse=privacidade">Conversar sobre privacidade ↗</Link></PageHero>
    <section className="section" id="dpo"><div className="shell"><SectionHeading eyebrow="DPO as a Service" title="Uma função de encarregado conectada às suas equipes." description="Apoio terceirizado para estruturar a interlocução sobre proteção de dados e acompanhar a governança de privacidade, com escopo e responsabilidades definidos em conjunto." /><div className="card-grid card-grid--two">
      <ServiceCard number="01" title="Atendimento e orientação" description="Organização dos pontos de contato e apoio às demandas que chegam à função de encarregado."><ul className="feature-list"><li>Estruturação do fluxo de solicitações de titulares.</li><li>Apoio ao registro, à triagem e ao acompanhamento de demandas.</li><li>Orientação às áreas sobre práticas e procedimentos de proteção de dados.</li><li>Apoio à interlocução com a autoridade de proteção de dados quando necessário, conforme o escopo.</li></ul></ServiceCard>
      <ServiceCard number="02" title="Governança e acompanhamento" description="Uma rotina para manter o programa de privacidade próximo das mudanças do negócio."><ul className="feature-list"><li>Reuniões e canais de atendimento com cadência acordada.</li><li>Acompanhamento do plano de ação e dos registros de decisões.</li><li>Apoio à análise de mudanças em processos que envolvam dados pessoais.</li><li>Articulação com as áreas responsáveis diante de ocorrências de privacidade.</li></ul></ServiceCard>
    </div><div className="content-prose"><p>O modelo de atendimento, os canais, a disponibilidade e as entregas são estabelecidos na proposta. A atuação do encarregado se conecta aos responsáveis internos e não substitui as decisões de gestão da organização.</p></div><Link className="button button--outline" href="/contato?interesse=dpo">Solicitar proposta de DPO ↗</Link></div></section>
    <section className="section section--tint" id="adequacao-lgpd"><div className="shell"><SectionHeading eyebrow="Adequação à LGPD" title="Um programa construído a partir da sua realidade." description="Combine as frentes necessárias para chegar a processos, registros e prioridades mais claros." /><div className="card-grid card-grid--two">{privacyServices.map((service, index) => <ServiceCard key={service.id} number={String(index + 1).padStart(2, "0")} title={service.title} description={service.description}><ul className="feature-list">{service.items.map(item => <li key={item}>{item}</li>)}</ul></ServiceCard>)}</div></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Como trabalhamos" title="Etapas claras. Responsabilidades definidas." description="A sequência e a profundidade são ajustadas à maturidade, ao porte e às prioridades do negócio." /><Steps items={[{title:"Entender o contexto",description:"Conhecer o negócio, as áreas, as atividades com dados pessoais e os materiais já disponíveis."},{title:"Mapear e priorizar",description:"Organizar os fluxos, identificar lacunas e construir um plano compatível com os riscos e recursos."},{title:"Construir e implementar",description:"Criar ou revisar documentos com as áreas, orientar procedimentos e acompanhar os entregáveis."},{title:"Acompanhar a evolução",description:"Revisar pendências, registrar evidências e ajustar o programa conforme o negócio evolui."}]} /></div></section>
    <section className="section section--navy"><div className="shell split-layout"><div><p className="page-kicker">Entregas que apoiam a rotina</p><h2>Documentação útil para quem precisa agir.</h2><p>O conjunto de entregáveis é definido no início do projeto. Cada documento deve refletir os processos avaliados e ter responsáveis por sua atualização.</p></div><ul className="feature-list"><li>Diagnóstico e plano de ação priorizado.</li><li>Inventário de dados e registro das operações de tratamento.</li><li>Avaliações de legítimo interesse, quando aplicáveis.</li><li>Políticas, avisos e procedimentos previstos no escopo.</li><li>Registros de orientações, decisões e acompanhamento.</li></ul></div></section>
    <section className="section"><div className="shell narrow"><SectionHeading eyebrow="Dúvidas frequentes" title="Entenda o trabalho antes de começar." /><FAQ items={privacyFaqs} /></div></section><CtaBand title="Qual é o próximo passo do seu programa de privacidade?" description="Conte em que estágio sua organização está e quais desafios precisam de atenção." href="/contato?interesse=privacidade" label="Conversar sobre meu cenário ↗" />
  </main>;
}
