import { PageHero, SectionHeading, Steps, FAQ } from "@/components/Editorial";
import NewsletterForm from "@/components/NewsletterForm";
import NewsletterArchive from "@/components/NewsletterArchive";
import { newsletterEditions } from "@/lib/site";

export const metadata = { title: "Newsletter", description: "Acompanhe as edições da newsletter Plataforma de Privacidade sobre governança, privacidade e segurança. Assine com confirmação por e-mail." };

export default function NewsletterPage() {
  return <main id="conteudo"><PageHero eyebrow="Newsletter / Conhecimento em movimento" title="Perspectivas para decisões mais conscientes." description="Um canal de relacionamento para acompanhar reflexões sobre governança de dados, privacidade e segurança da informação. Conteúdo demonstrativo para apresentar a experiência de assinatura."><div className="quote-panel"><p>Entender o contexto. Fazer as perguntas certas. Transformar conhecimento em ação.</p><a className="button button--navy" href="#assinar">Quero acompanhar ↗</a></div></PageHero>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Edições publicadas" title="Conhecimento para revisitar." description="Consulte as publicações e aprofunde os temas que fazem sentido para sua realidade." /><NewsletterArchive editions={newsletterEditions} /></div></section>
    <section className="section section--tint" id="assinar"><div className="shell split-layout"><div><p className="page-kicker">Sua assinatura, sua escolha</p><h2>Receba as próximas edições.</h2><p>A inscrição é gratuita e independente dos nossos serviços. Você confirma seu interesse por e-mail e pode cancelar a assinatura a qualquer momento.</p><div className="topic-tags"><span className="tag">Governança de dados</span><span className="tag">Privacidade</span><span className="tag">Segurança da informação</span><span className="tag">Cultura de proteção</span></div></div><NewsletterForm /></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Como funciona" title="Uma confirmação a mais. Mais controle para você." /><Steps items={[{title:"Informe seu e-mail",description:"Preencha o formulário e autorize o recebimento da newsletter."},{title:"Confirme sua escolha",description:"Abra o link de confirmação recebido e confirme a assinatura. O link expira em 24 horas."},{title:"Acompanhe as edições",description:"Sua assinatura fica ativa somente após a confirmação. O cancelamento estará disponível nos e-mails."}]} /></div></section>
    <section className="section section--tint"><div className="shell narrow"><FAQ items={[{question:"Não recebi o e-mail de confirmação. O que fazer?",answer:"Confira a pasta de spam e se o endereço foi digitado corretamente. Você pode repetir a inscrição para solicitar um novo link; nesse caso, utilize o mais recente. Se a dificuldade continuar, fale conosco pelo formulário de contato."},{question:"A assinatura é ativada ao preencher o formulário?",answer:"Não. O formulário solicita a inscrição, mas o cadastro só fica ativo após a confirmação pelo titular do e-mail. Abrir a página de confirmação, sem clicar no botão, também não ativa a assinatura."},{question:"Posso cancelar?",answer:"Sim. Use o link de cancelamento enviado por e-mail e confirme sua escolha. Você também pode solicitar o cancelamento no formulário de contato, na opção sobre dados pessoais."}]} /></div></section>
  </main>;
}
