import Link from "next/link";
import { PageHero, SectionHeading, ServiceCard, FAQ, CtaBand, Steps } from "@/components/Editorial";
import { trainingCatalog, trainingFaqs } from "@/lib/content";

export const metadata = { title: "Hub Educacional", description: "Palestras, minicursos, treinamentos sob medida e tabletop de resposta a incidentes e continuidade de negócios." };

export default function EducationPage() {
  return <main id="conteudo"><PageHero eyebrow="Hub Educacional" title="Conhecimento que prepara pessoas para agir." description="Palestras, minicursos, treinamentos sob medida e simulações para aproximar segurança, privacidade e continuidade das decisões do dia a dia."><p className="page-kicker">Aprender. Praticar. Evoluir.</p><p>Escolha uma sensibilização, aprofunde um tema ou coloque a coordenação entre equipes à prova em um cenário simulado.</p><Link className="button button--navy" href="/contato?interesse=treinamento">Planejar uma capacitação ↗</Link></PageHero>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Formatos de aprendizagem" title="Diferentes caminhos para o objetivo da sua equipe." description="Conteúdo, duração, modalidade, agenda e materiais são definidos de acordo com o público e com o escopo contratado." /><nav aria-label="Formatos de capacitação" className="topic-tags">{trainingCatalog.map(training => <a className="tag tag--link" href={`#${training.id}`} key={training.id}>{training.title} ↓</a>)}</nav></div></section>
    {trainingCatalog.map((training, index) => <section id={training.id} className={`section${index % 2 === 0 ? " section--tint" : ""}`} key={training.id}><div className="shell split-layout"><div><p className="page-kicker">{training.format}</p><h2>{training.title}</h2><p>{training.description}</p><p><strong>Para quem:</strong> {training.audience}</p><Link className="button button--outline" href={`/contato?interesse=treinamento&formato=${training.id}`}>Solicitar proposta deste formato ↗</Link></div><ServiceCard title="O que pode fazer parte da atividade"><ul className="feature-list">{training.topics.map(topic => <li key={topic}>{topic}</li>)}</ul><p><strong>Entrega proposta:</strong> {training.deliverable}</p></ServiceCard></div></section>)}
    <section className="section section--navy"><div className="shell"><SectionHeading eyebrow="Do cenário à melhoria" title="Como acontece um exercício tabletop?" description="Os participantes discutem um cenário fictício que evolui ao longo da sessão. A dinâmica observa como as equipes interpretam o problema, compartilham informações e tomam decisões." /><div className="card-grid"><ServiceCard number="01" title="Preparação" description="Definição do objetivo, dos participantes, dos processos envolvidos e das regras do exercício." /><ServiceCard number="02" title="Simulação guiada" description="Situações progressivas para discutir responsabilidades, comunicação e prioridades." /><ServiceCard number="03" title="Debriefing e ações" description="Conversa sobre o que funcionou, quais dúvidas apareceram e quais melhorias devem ser priorizadas." /></div><p>O tabletop é uma simulação de decisões por discussão. A atividade não pressupõe ataques, alterações em sistemas ou interrupção real da operação.</p></div></section>
    <section className="section"><div className="shell"><SectionHeading eyebrow="Construção do programa" title="A capacitação começa pelo seu contexto." /><Steps items={[{title:"Definir o objetivo",description:"Identificar o que as pessoas precisam compreender, praticar ou decidir melhor."},{title:"Conhecer o público",description:"Entender a experiência dos participantes, suas rotinas e os desafios da organização."},{title:"Construir a experiência",description:"Acordar programa, exemplos, materiais, formato, duração e dinâmica."},{title:"Conectar ao trabalho",description:"Consolidar aprendizados e, quando previsto, registrar melhorias e avaliar resultados."}]} /></div></section>
    <section className="section section--tint"><div className="shell narrow"><SectionHeading eyebrow="Dúvidas frequentes" title="Prepare a atividade com informações claras." /><FAQ items={trainingFaqs} /></div></section><CtaBand title="Que habilidade sua equipe precisa desenvolver?" description="Informe o público, os temas de interesse e o objetivo da atividade para construirmos uma proposta." href="/contato?interesse=treinamento" label="Montar uma proposta de treinamento ↗" />
  </main>;
}
